import { MigrationInterface, QueryRunner } from "typeorm";

export class AssignmentQuestion41608649427876 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
        insert into public.assignment_question ("assignmentId", content) values (365, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (204, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (188, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (977, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (547, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (707, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (997, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (444, 'Training');
insert into public.assignment_question ("assignmentId", content) values (433, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (718, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (877, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (587, 'Support');
insert into public.assignment_question ("assignmentId", content) values (606, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (658, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (876, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (78, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (295, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (497, 'Training');
insert into public.assignment_question ("assignmentId", content) values (722, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (115, 'Support');
insert into public.assignment_question ("assignmentId", content) values (496, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (667, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (595, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (162, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (704, 'Training');
insert into public.assignment_question ("assignmentId", content) values (916, 'Training');
insert into public.assignment_question ("assignmentId", content) values (278, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (751, 'Services');
insert into public.assignment_question ("assignmentId", content) values (572, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (780, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (829, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (570, 'Services');
insert into public.assignment_question ("assignmentId", content) values (711, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (559, 'Services');
insert into public.assignment_question ("assignmentId", content) values (645, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (624, 'Support');
insert into public.assignment_question ("assignmentId", content) values (197, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (332, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (821, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (812, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (436, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (995, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (794, 'Services');
insert into public.assignment_question ("assignmentId", content) values (180, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (300, 'Support');
insert into public.assignment_question ("assignmentId", content) values (26, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (689, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (896, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (329, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (126, 'Services');
insert into public.assignment_question ("assignmentId", content) values (739, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (582, 'Services');
insert into public.assignment_question ("assignmentId", content) values (939, 'Support');
insert into public.assignment_question ("assignmentId", content) values (311, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (496, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (426, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (992, 'Services');
insert into public.assignment_question ("assignmentId", content) values (302, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (378, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (748, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (569, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (481, 'Support');
insert into public.assignment_question ("assignmentId", content) values (553, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (172, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (27, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (579, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (804, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (101, 'Services');
insert into public.assignment_question ("assignmentId", content) values (722, 'Support');
insert into public.assignment_question ("assignmentId", content) values (709, 'Services');
insert into public.assignment_question ("assignmentId", content) values (876, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (193, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (562, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (791, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (633, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (339, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (801, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (225, 'Support');
insert into public.assignment_question ("assignmentId", content) values (889, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (441, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (375, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (175, 'Training');
insert into public.assignment_question ("assignmentId", content) values (50, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (421, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (985, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (766, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (47, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (316, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (405, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (510, 'Services');
insert into public.assignment_question ("assignmentId", content) values (864, 'Support');
insert into public.assignment_question ("assignmentId", content) values (764, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (55, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (943, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (977, 'Support');
insert into public.assignment_question ("assignmentId", content) values (321, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (764, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (43, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (722, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (815, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (832, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (311, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (147, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (417, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (351, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (799, 'Services');
insert into public.assignment_question ("assignmentId", content) values (603, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (786, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (233, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (669, 'Services');
insert into public.assignment_question ("assignmentId", content) values (244, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (446, 'Services');
insert into public.assignment_question ("assignmentId", content) values (74, 'Support');
insert into public.assignment_question ("assignmentId", content) values (597, 'Services');
insert into public.assignment_question ("assignmentId", content) values (292, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (244, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (775, 'Support');
insert into public.assignment_question ("assignmentId", content) values (401, 'Training');
insert into public.assignment_question ("assignmentId", content) values (65, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (387, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (117, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (948, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (681, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (185, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (214, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (42, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (290, 'Services');
insert into public.assignment_question ("assignmentId", content) values (246, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (867, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (568, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (475, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (759, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (471, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (133, 'Services');
insert into public.assignment_question ("assignmentId", content) values (872, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (908, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (777, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (473, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (69, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (774, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (580, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (558, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (201, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (240, 'Training');
insert into public.assignment_question ("assignmentId", content) values (582, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (895, 'Services');
insert into public.assignment_question ("assignmentId", content) values (342, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (211, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (463, 'Training');
insert into public.assignment_question ("assignmentId", content) values (510, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (982, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (541, 'Support');
insert into public.assignment_question ("assignmentId", content) values (400, 'Support');
insert into public.assignment_question ("assignmentId", content) values (947, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (175, 'Services');
insert into public.assignment_question ("assignmentId", content) values (156, 'Services');
insert into public.assignment_question ("assignmentId", content) values (400, 'Support');
insert into public.assignment_question ("assignmentId", content) values (570, 'Support');
insert into public.assignment_question ("assignmentId", content) values (399, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (825, 'Support');
insert into public.assignment_question ("assignmentId", content) values (517, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (429, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (651, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (752, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (648, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (280, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (405, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (415, 'Training');
insert into public.assignment_question ("assignmentId", content) values (981, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (651, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (723, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (658, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (763, 'Training');
insert into public.assignment_question ("assignmentId", content) values (698, 'Services');
insert into public.assignment_question ("assignmentId", content) values (612, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (442, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (564, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (200, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (775, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (116, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (127, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (262, 'Services');
insert into public.assignment_question ("assignmentId", content) values (550, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (944, 'Training');
insert into public.assignment_question ("assignmentId", content) values (891, 'Training');
insert into public.assignment_question ("assignmentId", content) values (904, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (945, 'Support');
insert into public.assignment_question ("assignmentId", content) values (618, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (342, 'Training');
insert into public.assignment_question ("assignmentId", content) values (552, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (162, 'Services');
insert into public.assignment_question ("assignmentId", content) values (421, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (643, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (504, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (366, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (791, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (677, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (566, 'Support');
insert into public.assignment_question ("assignmentId", content) values (54, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (936, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (970, 'Training');
insert into public.assignment_question ("assignmentId", content) values (27, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (931, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (645, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (903, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (41, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (151, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (430, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (979, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (350, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (66, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (704, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (171, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (80, 'Services');
insert into public.assignment_question ("assignmentId", content) values (732, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (106, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (768, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (741, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (342, 'Support');
insert into public.assignment_question ("assignmentId", content) values (133, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (635, 'Training');
insert into public.assignment_question ("assignmentId", content) values (261, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (126, 'Support');
insert into public.assignment_question ("assignmentId", content) values (549, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (566, 'Support');
insert into public.assignment_question ("assignmentId", content) values (890, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (376, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (811, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (167, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (184, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (536, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (542, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (579, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (814, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (771, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (751, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (694, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (844, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (17, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (901, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (362, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (901, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (286, 'Training');
insert into public.assignment_question ("assignmentId", content) values (318, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (286, 'Training');
insert into public.assignment_question ("assignmentId", content) values (621, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (971, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (129, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (33, 'Support');
insert into public.assignment_question ("assignmentId", content) values (88, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (46, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (859, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (200, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (348, 'Services');
insert into public.assignment_question ("assignmentId", content) values (108, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (811, 'Support');
insert into public.assignment_question ("assignmentId", content) values (255, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (165, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (952, 'Training');
insert into public.assignment_question ("assignmentId", content) values (564, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (623, 'Support');
insert into public.assignment_question ("assignmentId", content) values (898, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (127, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (774, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (604, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (478, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (36, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (880, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (734, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (334, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (935, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (496, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (752, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (127, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (622, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (30, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (42, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (554, 'Services');
insert into public.assignment_question ("assignmentId", content) values (727, 'Services');
insert into public.assignment_question ("assignmentId", content) values (287, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (902, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (996, 'Services');
insert into public.assignment_question ("assignmentId", content) values (823, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (389, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (923, 'Training');
insert into public.assignment_question ("assignmentId", content) values (819, 'Training');
insert into public.assignment_question ("assignmentId", content) values (964, 'Support');
insert into public.assignment_question ("assignmentId", content) values (695, 'Services');
insert into public.assignment_question ("assignmentId", content) values (40, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (472, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (694, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (563, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (795, 'Services');
insert into public.assignment_question ("assignmentId", content) values (749, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (463, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (969, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (399, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (624, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (568, 'Training');
insert into public.assignment_question ("assignmentId", content) values (800, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (883, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (43, 'Services');
insert into public.assignment_question ("assignmentId", content) values (197, 'Services');
insert into public.assignment_question ("assignmentId", content) values (892, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (834, 'Support');
insert into public.assignment_question ("assignmentId", content) values (980, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (474, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (739, 'Support');
insert into public.assignment_question ("assignmentId", content) values (550, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (721, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (364, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (780, 'Training');
insert into public.assignment_question ("assignmentId", content) values (268, 'Support');
insert into public.assignment_question ("assignmentId", content) values (633, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (443, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (907, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (24, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (6, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (442, 'Training');
insert into public.assignment_question ("assignmentId", content) values (966, 'Services');
insert into public.assignment_question ("assignmentId", content) values (181, 'Training');
insert into public.assignment_question ("assignmentId", content) values (634, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (641, 'Support');
insert into public.assignment_question ("assignmentId", content) values (936, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (397, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (368, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (45, 'Services');
insert into public.assignment_question ("assignmentId", content) values (544, 'Support');
insert into public.assignment_question ("assignmentId", content) values (191, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (721, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (106, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (71, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (194, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (100, 'Training');
insert into public.assignment_question ("assignmentId", content) values (421, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (869, 'Services');
insert into public.assignment_question ("assignmentId", content) values (711, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (846, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (646, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (66, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (541, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (285, 'Services');
insert into public.assignment_question ("assignmentId", content) values (296, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (219, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (485, 'Training');
insert into public.assignment_question ("assignmentId", content) values (750, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (741, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (346, 'Training');
insert into public.assignment_question ("assignmentId", content) values (511, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (25, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (682, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (611, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (885, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (788, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (266, 'Training');
insert into public.assignment_question ("assignmentId", content) values (637, 'Training');
insert into public.assignment_question ("assignmentId", content) values (685, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (653, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (119, 'Support');
insert into public.assignment_question ("assignmentId", content) values (111, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (965, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (649, 'Support');
insert into public.assignment_question ("assignmentId", content) values (994, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (384, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (396, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (283, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (444, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (846, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (3, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (158, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (417, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (575, 'Training');
insert into public.assignment_question ("assignmentId", content) values (408, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (630, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (935, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (746, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (975, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (2, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (398, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (60, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (867, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (829, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (839, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (671, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (667, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (234, 'Training');
insert into public.assignment_question ("assignmentId", content) values (82, 'Support');
insert into public.assignment_question ("assignmentId", content) values (50, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (595, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (530, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (857, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (639, 'Support');
insert into public.assignment_question ("assignmentId", content) values (475, 'Training');
insert into public.assignment_question ("assignmentId", content) values (267, 'Support');
insert into public.assignment_question ("assignmentId", content) values (269, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (65, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (98, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (745, 'Services');
insert into public.assignment_question ("assignmentId", content) values (587, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (437, 'Training');
insert into public.assignment_question ("assignmentId", content) values (632, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (56, 'Training');
insert into public.assignment_question ("assignmentId", content) values (840, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (867, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (995, 'Support');
insert into public.assignment_question ("assignmentId", content) values (256, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (85, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (937, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (723, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (304, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (429, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (502, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (257, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (890, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (695, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (977, 'Training');
insert into public.assignment_question ("assignmentId", content) values (522, 'Training');
insert into public.assignment_question ("assignmentId", content) values (490, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (351, 'Services');
insert into public.assignment_question ("assignmentId", content) values (151, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (165, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (329, 'Services');
insert into public.assignment_question ("assignmentId", content) values (210, 'Services');
insert into public.assignment_question ("assignmentId", content) values (349, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (451, 'Training');
insert into public.assignment_question ("assignmentId", content) values (871, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (592, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (330, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (525, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (876, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (233, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (190, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (724, 'Training');
insert into public.assignment_question ("assignmentId", content) values (926, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (136, 'Support');
insert into public.assignment_question ("assignmentId", content) values (907, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (87, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (115, 'Support');
insert into public.assignment_question ("assignmentId", content) values (984, 'Training');
insert into public.assignment_question ("assignmentId", content) values (988, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (636, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (691, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (508, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (570, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (154, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (138, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (815, 'Support');
insert into public.assignment_question ("assignmentId", content) values (732, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (558, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (186, 'Training');
insert into public.assignment_question ("assignmentId", content) values (841, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (591, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (714, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (370, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (192, 'Support');
insert into public.assignment_question ("assignmentId", content) values (547, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (839, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (578, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (384, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (790, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (446, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (135, 'Support');
insert into public.assignment_question ("assignmentId", content) values (823, 'Support');
insert into public.assignment_question ("assignmentId", content) values (430, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (330, 'Training');
insert into public.assignment_question ("assignmentId", content) values (399, 'Training');
insert into public.assignment_question ("assignmentId", content) values (644, 'Support');
insert into public.assignment_question ("assignmentId", content) values (808, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (353, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (917, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (369, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (956, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (128, 'Services');
insert into public.assignment_question ("assignmentId", content) values (104, 'Services');
insert into public.assignment_question ("assignmentId", content) values (250, 'Support');
insert into public.assignment_question ("assignmentId", content) values (778, 'Support');
insert into public.assignment_question ("assignmentId", content) values (926, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (552, 'Support');
insert into public.assignment_question ("assignmentId", content) values (267, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (797, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (31, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (62, 'Services');
insert into public.assignment_question ("assignmentId", content) values (14, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (276, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (824, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (597, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (736, 'Services');
insert into public.assignment_question ("assignmentId", content) values (113, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (338, 'Services');
insert into public.assignment_question ("assignmentId", content) values (928, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (893, 'Support');
insert into public.assignment_question ("assignmentId", content) values (789, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (460, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (989, 'Support');
insert into public.assignment_question ("assignmentId", content) values (230, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (866, 'Services');
insert into public.assignment_question ("assignmentId", content) values (868, 'Services');
insert into public.assignment_question ("assignmentId", content) values (837, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (816, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (834, 'Services');
insert into public.assignment_question ("assignmentId", content) values (51, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (777, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (605, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (122, 'Support');
insert into public.assignment_question ("assignmentId", content) values (872, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (79, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (514, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (670, 'Services');
insert into public.assignment_question ("assignmentId", content) values (294, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (168, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (552, 'Training');
insert into public.assignment_question ("assignmentId", content) values (881, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (166, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (766, 'Training');
insert into public.assignment_question ("assignmentId", content) values (623, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (435, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (138, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (887, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (416, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (41, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (259, 'Support');
insert into public.assignment_question ("assignmentId", content) values (776, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (75, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (445, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (267, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (380, 'Training');
insert into public.assignment_question ("assignmentId", content) values (449, 'Support');
insert into public.assignment_question ("assignmentId", content) values (800, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (275, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (14, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (722, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (531, 'Training');
insert into public.assignment_question ("assignmentId", content) values (736, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (153, 'Training');
insert into public.assignment_question ("assignmentId", content) values (657, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (132, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (449, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (415, 'Services');
insert into public.assignment_question ("assignmentId", content) values (271, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (803, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (233, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (748, 'Support');
insert into public.assignment_question ("assignmentId", content) values (90, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (8, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (597, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (671, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (558, 'Services');
insert into public.assignment_question ("assignmentId", content) values (636, 'Support');
insert into public.assignment_question ("assignmentId", content) values (739, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (124, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (922, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (543, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (463, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (642, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (942, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (528, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (889, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (458, 'Training');
insert into public.assignment_question ("assignmentId", content) values (505, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (506, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (689, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (30, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (150, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (963, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (896, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (56, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (222, 'Support');
insert into public.assignment_question ("assignmentId", content) values (194, 'Training');
insert into public.assignment_question ("assignmentId", content) values (127, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (660, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (843, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (144, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (622, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (303, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (319, 'Support');
insert into public.assignment_question ("assignmentId", content) values (51, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (360, 'Training');
insert into public.assignment_question ("assignmentId", content) values (944, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (952, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (702, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (547, 'Training');
insert into public.assignment_question ("assignmentId", content) values (466, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (130, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (799, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (661, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (675, 'Support');
insert into public.assignment_question ("assignmentId", content) values (142, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (746, 'Support');
insert into public.assignment_question ("assignmentId", content) values (19, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (480, 'Training');
insert into public.assignment_question ("assignmentId", content) values (422, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (692, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (779, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (458, 'Services');
insert into public.assignment_question ("assignmentId", content) values (68, 'Services');
insert into public.assignment_question ("assignmentId", content) values (956, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (42, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (298, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (378, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (964, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (798, 'Training');
insert into public.assignment_question ("assignmentId", content) values (610, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (185, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (118, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (387, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (496, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (755, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (737, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (138, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (219, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (67, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (91, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (310, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (244, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (235, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (565, 'Training');
insert into public.assignment_question ("assignmentId", content) values (276, 'Services');
insert into public.assignment_question ("assignmentId", content) values (643, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (893, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (353, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (585, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (189, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (840, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (165, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (684, 'Services');
insert into public.assignment_question ("assignmentId", content) values (163, 'Services');
insert into public.assignment_question ("assignmentId", content) values (183, 'Training');
insert into public.assignment_question ("assignmentId", content) values (972, 'Services');
insert into public.assignment_question ("assignmentId", content) values (622, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (896, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (304, 'Support');
insert into public.assignment_question ("assignmentId", content) values (87, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (527, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (718, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (370, 'Support');
insert into public.assignment_question ("assignmentId", content) values (939, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (705, 'Training');
insert into public.assignment_question ("assignmentId", content) values (856, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (169, 'Training');
insert into public.assignment_question ("assignmentId", content) values (497, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (861, 'Support');
insert into public.assignment_question ("assignmentId", content) values (68, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (431, 'Services');
insert into public.assignment_question ("assignmentId", content) values (594, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (848, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (694, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (311, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (11, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (667, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (553, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (696, 'Training');
insert into public.assignment_question ("assignmentId", content) values (697, 'Training');
insert into public.assignment_question ("assignmentId", content) values (87, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (862, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (727, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (553, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (546, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (571, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (591, 'Services');
insert into public.assignment_question ("assignmentId", content) values (478, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (698, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (91, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (815, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (60, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (154, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (297, 'Services');
insert into public.assignment_question ("assignmentId", content) values (409, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (828, 'Training');
insert into public.assignment_question ("assignmentId", content) values (640, 'Training');
insert into public.assignment_question ("assignmentId", content) values (554, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (932, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (875, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (61, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (880, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (95, 'Training');
insert into public.assignment_question ("assignmentId", content) values (68, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (601, 'Training');
insert into public.assignment_question ("assignmentId", content) values (285, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (894, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (751, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (160, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (521, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (253, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (589, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (720, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (488, 'Support');
insert into public.assignment_question ("assignmentId", content) values (853, 'Support');
insert into public.assignment_question ("assignmentId", content) values (719, 'Training');
insert into public.assignment_question ("assignmentId", content) values (25, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (390, 'Services');
insert into public.assignment_question ("assignmentId", content) values (117, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (58, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (910, 'Services');
insert into public.assignment_question ("assignmentId", content) values (253, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (583, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (118, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (988, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (651, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (966, 'Support');
insert into public.assignment_question ("assignmentId", content) values (999, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (418, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (673, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (635, 'Services');
insert into public.assignment_question ("assignmentId", content) values (385, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (277, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (783, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (225, 'Training');
insert into public.assignment_question ("assignmentId", content) values (912, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (599, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (685, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (774, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (969, 'Training');
insert into public.assignment_question ("assignmentId", content) values (567, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (721, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (188, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (799, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (922, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (179, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (698, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (71, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (303, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (653, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (907, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (406, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (596, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (825, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (122, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (285, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (176, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (693, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (114, 'Services');
insert into public.assignment_question ("assignmentId", content) values (512, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (833, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (597, 'Support');
insert into public.assignment_question ("assignmentId", content) values (682, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (131, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (307, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (522, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (1000, 'Training');
insert into public.assignment_question ("assignmentId", content) values (580, 'Training');
insert into public.assignment_question ("assignmentId", content) values (955, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (266, 'Services');
insert into public.assignment_question ("assignmentId", content) values (668, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (596, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (584, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (865, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (35, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (214, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (192, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (356, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (746, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (698, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (650, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (557, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (953, 'Training');
insert into public.assignment_question ("assignmentId", content) values (580, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (314, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (29, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (897, 'Services');
insert into public.assignment_question ("assignmentId", content) values (4, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (768, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (29, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (29, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (817, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (187, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (963, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (979, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (15, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (551, 'Training');
insert into public.assignment_question ("assignmentId", content) values (718, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (423, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (999, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (93, 'Support');
insert into public.assignment_question ("assignmentId", content) values (419, 'Services');
insert into public.assignment_question ("assignmentId", content) values (566, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (817, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (455, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (940, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (660, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (581, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (558, 'Services');
insert into public.assignment_question ("assignmentId", content) values (277, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (620, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (99, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (211, 'Support');
insert into public.assignment_question ("assignmentId", content) values (259, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (476, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (565, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (224, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (732, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (673, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (435, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (410, 'Training');
insert into public.assignment_question ("assignmentId", content) values (383, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (122, 'Training');
insert into public.assignment_question ("assignmentId", content) values (57, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (325, 'Training');
insert into public.assignment_question ("assignmentId", content) values (415, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (948, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (764, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (107, 'Support');
insert into public.assignment_question ("assignmentId", content) values (568, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (76, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (870, 'Services');
insert into public.assignment_question ("assignmentId", content) values (40, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (510, 'Support');
insert into public.assignment_question ("assignmentId", content) values (659, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (536, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (655, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (749, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (235, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (685, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (740, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (295, 'Services');
insert into public.assignment_question ("assignmentId", content) values (510, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (324, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (546, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (639, 'Services');
insert into public.assignment_question ("assignmentId", content) values (723, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (36, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (980, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (642, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (954, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (703, 'Training');
insert into public.assignment_question ("assignmentId", content) values (990, 'Support');
insert into public.assignment_question ("assignmentId", content) values (840, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (994, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (702, 'Training');
insert into public.assignment_question ("assignmentId", content) values (779, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (387, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (240, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (284, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (788, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (504, 'Services');
insert into public.assignment_question ("assignmentId", content) values (788, 'Services');
insert into public.assignment_question ("assignmentId", content) values (324, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (151, 'Training');
insert into public.assignment_question ("assignmentId", content) values (721, 'Services');
insert into public.assignment_question ("assignmentId", content) values (775, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (68, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (402, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (26, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (196, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (650, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (539, 'Services');
insert into public.assignment_question ("assignmentId", content) values (985, 'Services');
insert into public.assignment_question ("assignmentId", content) values (299, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (552, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (801, 'Services');
insert into public.assignment_question ("assignmentId", content) values (793, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (836, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (266, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (226, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (760, 'Training');
insert into public.assignment_question ("assignmentId", content) values (212, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (750, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (448, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (118, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (801, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (410, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (400, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (270, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (20, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (353, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (268, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (535, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (750, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (496, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (268, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (82, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (852, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (775, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (324, 'Training');
insert into public.assignment_question ("assignmentId", content) values (469, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (756, 'Support');
insert into public.assignment_question ("assignmentId", content) values (841, 'Services');
insert into public.assignment_question ("assignmentId", content) values (598, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (293, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (906, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (48, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (811, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (865, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (827, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (431, 'Services');
insert into public.assignment_question ("assignmentId", content) values (259, 'Services');
insert into public.assignment_question ("assignmentId", content) values (692, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (559, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (531, 'Services');
insert into public.assignment_question ("assignmentId", content) values (154, 'Support');
insert into public.assignment_question ("assignmentId", content) values (705, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (913, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (588, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (481, 'Training');
insert into public.assignment_question ("assignmentId", content) values (308, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (822, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (817, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (116, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (439, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (148, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (985, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (614, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (84, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (682, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (356, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (16, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (611, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (302, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (758, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (857, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (989, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (384, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (584, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (543, 'Services');
insert into public.assignment_question ("assignmentId", content) values (169, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (106, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (339, 'Training');
insert into public.assignment_question ("assignmentId", content) values (196, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (977, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (584, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (63, 'Services');
insert into public.assignment_question ("assignmentId", content) values (185, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (270, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (185, 'Support');
insert into public.assignment_question ("assignmentId", content) values (30, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (542, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (828, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (305, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (767, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (79, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (150, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (129, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (759, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (926, 'Training');
insert into public.assignment_question ("assignmentId", content) values (149, 'Support');
insert into public.assignment_question ("assignmentId", content) values (559, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (543, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (394, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (757, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (873, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (863, 'Training');
insert into public.assignment_question ("assignmentId", content) values (305, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (228, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (705, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (981, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (759, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (935, 'Support');
insert into public.assignment_question ("assignmentId", content) values (615, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (46, 'Training');
insert into public.assignment_question ("assignmentId", content) values (556, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (670, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (461, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (344, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (278, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (771, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (301, 'Support');
insert into public.assignment_question ("assignmentId", content) values (627, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (680, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (760, 'Training');
insert into public.assignment_question ("assignmentId", content) values (204, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (590, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (583, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (404, 'Training');
insert into public.assignment_question ("assignmentId", content) values (810, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (258, 'Training');
insert into public.assignment_question ("assignmentId", content) values (203, 'Services');
insert into public.assignment_question ("assignmentId", content) values (772, 'Training');
insert into public.assignment_question ("assignmentId", content) values (735, 'Services');
insert into public.assignment_question ("assignmentId", content) values (42, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (840, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (40, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (262, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (701, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (500, 'Accounting');
insert into public.assignment_question ("assignmentId", content) values (331, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (37, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (790, 'Services');
insert into public.assignment_question ("assignmentId", content) values (353, 'Services');
insert into public.assignment_question ("assignmentId", content) values (788, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (54, 'Services');
insert into public.assignment_question ("assignmentId", content) values (549, 'Research and Development');
insert into public.assignment_question ("assignmentId", content) values (533, 'Product Management');
insert into public.assignment_question ("assignmentId", content) values (330, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (14, 'Engineering');
insert into public.assignment_question ("assignmentId", content) values (21, 'Support');
insert into public.assignment_question ("assignmentId", content) values (486, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (1000, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (816, 'Services');
insert into public.assignment_question ("assignmentId", content) values (977, 'Training');
insert into public.assignment_question ("assignmentId", content) values (315, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (44, 'Support');
insert into public.assignment_question ("assignmentId", content) values (910, 'Legal');
insert into public.assignment_question ("assignmentId", content) values (104, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (593, 'Marketing');
insert into public.assignment_question ("assignmentId", content) values (221, 'Services');
insert into public.assignment_question ("assignmentId", content) values (915, 'Training');
insert into public.assignment_question ("assignmentId", content) values (725, 'Services');
insert into public.assignment_question ("assignmentId", content) values (934, 'Business Development');
insert into public.assignment_question ("assignmentId", content) values (341, 'Sales');
insert into public.assignment_question ("assignmentId", content) values (318, 'Human Resources');
insert into public.assignment_question ("assignmentId", content) values (270, 'Services');
        `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
