import { MigrationInterface, QueryRunner } from "typeorm";

export class AssignmentQuestion31608649376551 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
        insert into public.assignment_question ("assignmentId", content) values (731, 'Manat');
insert into public.assignment_question ("assignmentId", content) values (672, 'Smokvica');
insert into public.assignment_question ("assignmentId", content) values (558, 'Nunguan');
insert into public.assignment_question ("assignmentId", content) values (603, 'Kalá Déndra');
insert into public.assignment_question ("assignmentId", content) values (503, 'Chiri-Yurt');
insert into public.assignment_question ("assignmentId", content) values (35, 'Senduro');
insert into public.assignment_question ("assignmentId", content) values (549, 'Caotang');
insert into public.assignment_question ("assignmentId", content) values (837, 'Czerwin');
insert into public.assignment_question ("assignmentId", content) values (847, 'Port-Gentil');
insert into public.assignment_question ("assignmentId", content) values (262, 'Kalawit');
insert into public.assignment_question ("assignmentId", content) values (236, 'Várzea Paulista');
insert into public.assignment_question ("assignmentId", content) values (803, 'Loga');
insert into public.assignment_question ("assignmentId", content) values (542, 'Baltasar Brum');
insert into public.assignment_question ("assignmentId", content) values (589, 'Hrochův Týnec');
insert into public.assignment_question ("assignmentId", content) values (559, 'Patong');
insert into public.assignment_question ("assignmentId", content) values (914, 'Panggungsari');
insert into public.assignment_question ("assignmentId", content) values (701, 'Rättvik');
insert into public.assignment_question ("assignmentId", content) values (678, 'Mopti');
insert into public.assignment_question ("assignmentId", content) values (304, 'Loudi');
insert into public.assignment_question ("assignmentId", content) values (903, 'Zruč nad Sázavou');
insert into public.assignment_question ("assignmentId", content) values (473, 'Vila Nova');
insert into public.assignment_question ("assignmentId", content) values (551, 'Guangming');
insert into public.assignment_question ("assignmentId", content) values (931, 'Tawun');
insert into public.assignment_question ("assignmentId", content) values (858, 'Huilong');
insert into public.assignment_question ("assignmentId", content) values (725, 'Songwon');
insert into public.assignment_question ("assignmentId", content) values (808, 'Porto Formoso');
insert into public.assignment_question ("assignmentId", content) values (559, 'Tangzha');
insert into public.assignment_question ("assignmentId", content) values (883, 'Tiandu');
insert into public.assignment_question ("assignmentId", content) values (11, 'Al Bāriqīyah');
insert into public.assignment_question ("assignmentId", content) values (369, 'Mosteiros');
insert into public.assignment_question ("assignmentId", content) values (29, 'Alvand');
insert into public.assignment_question ("assignmentId", content) values (253, 'Krasnoarmeysk');
insert into public.assignment_question ("assignmentId", content) values (520, 'Łubowo');
insert into public.assignment_question ("assignmentId", content) values (735, 'Pangu');
insert into public.assignment_question ("assignmentId", content) values (135, 'Jarash');
insert into public.assignment_question ("assignmentId", content) values (314, 'Pöytyä');
insert into public.assignment_question ("assignmentId", content) values (499, 'Caen');
insert into public.assignment_question ("assignmentId", content) values (820, 'Horad Krychaw');
insert into public.assignment_question ("assignmentId", content) values (682, 'Mbouda');
insert into public.assignment_question ("assignmentId", content) values (838, 'Sandviken');
insert into public.assignment_question ("assignmentId", content) values (488, 'Guilhabreu');
insert into public.assignment_question ("assignmentId", content) values (439, 'Hazlov');
insert into public.assignment_question ("assignmentId", content) values (566, 'Jenggawah');
insert into public.assignment_question ("assignmentId", content) values (399, 'Pulau Pinang');
insert into public.assignment_question ("assignmentId", content) values (955, 'Stavropol’');
insert into public.assignment_question ("assignmentId", content) values (623, 'Kubang');
insert into public.assignment_question ("assignmentId", content) values (264, 'Chengxi');
insert into public.assignment_question ("assignmentId", content) values (49, 'Du’ermenqin');
insert into public.assignment_question ("assignmentId", content) values (947, 'Dolgoderevenskoye');
insert into public.assignment_question ("assignmentId", content) values (463, 'Kembé');
insert into public.assignment_question ("assignmentId", content) values (936, 'Mastaiciai');
insert into public.assignment_question ("assignmentId", content) values (140, 'Xiaxindian');
insert into public.assignment_question ("assignmentId", content) values (692, 'Kubangeceng');
insert into public.assignment_question ("assignmentId", content) values (68, 'San Bernardo');
insert into public.assignment_question ("assignmentId", content) values (344, 'Kuala Lumpur');
insert into public.assignment_question ("assignmentId", content) values (913, 'Melgar');
insert into public.assignment_question ("assignmentId", content) values (476, 'Al Wajh');
insert into public.assignment_question ("assignmentId", content) values (156, 'Villa Bustos');
insert into public.assignment_question ("assignmentId", content) values (175, 'Barabedang');
insert into public.assignment_question ("assignmentId", content) values (827, 'Psygansu');
insert into public.assignment_question ("assignmentId", content) values (480, 'Haiyang');
insert into public.assignment_question ("assignmentId", content) values (456, 'Mandepa Barat');
insert into public.assignment_question ("assignmentId", content) values (69, 'Budakovo');
insert into public.assignment_question ("assignmentId", content) values (563, 'Kalayemule');
insert into public.assignment_question ("assignmentId", content) values (624, 'Guiwu');
insert into public.assignment_question ("assignmentId", content) values (288, 'Puerto Aisén');
insert into public.assignment_question ("assignmentId", content) values (550, 'Lianghekou');
insert into public.assignment_question ("assignmentId", content) values (810, 'Castro Barros');
insert into public.assignment_question ("assignmentId", content) values (36, 'Doghs');
insert into public.assignment_question ("assignmentId", content) values (500, 'Rzozów');
insert into public.assignment_question ("assignmentId", content) values (134, 'Himanka');
insert into public.assignment_question ("assignmentId", content) values (617, 'Korobitsyno');
insert into public.assignment_question ("assignmentId", content) values (747, 'Dayuanhuizu');
insert into public.assignment_question ("assignmentId", content) values (595, 'Klobuky');
insert into public.assignment_question ("assignmentId", content) values (931, 'Brocēni');
insert into public.assignment_question ("assignmentId", content) values (541, 'Dalian');
insert into public.assignment_question ("assignmentId", content) values (374, 'Bordeaux');
insert into public.assignment_question ("assignmentId", content) values (57, 'Aguadulce');
insert into public.assignment_question ("assignmentId", content) values (601, 'Grästorp');
insert into public.assignment_question ("assignmentId", content) values (616, 'Lakhdenpokh’ya');
insert into public.assignment_question ("assignmentId", content) values (719, 'Abelheira');
insert into public.assignment_question ("assignmentId", content) values (121, 'Pamakayo');
insert into public.assignment_question ("assignmentId", content) values (45, 'Śródmieście');
insert into public.assignment_question ("assignmentId", content) values (982, 'Tulsa');
insert into public.assignment_question ("assignmentId", content) values (534, 'Castries');
insert into public.assignment_question ("assignmentId", content) values (58, 'Bochum');
insert into public.assignment_question ("assignmentId", content) values (11, 'Ar Rudayyif');
insert into public.assignment_question ("assignmentId", content) values (256, 'Shidu');
insert into public.assignment_question ("assignmentId", content) values (881, 'Fort Worth');
insert into public.assignment_question ("assignmentId", content) values (452, 'Nikolo-Pavlovskoye');
insert into public.assignment_question ("assignmentId", content) values (136, 'Maştağa');
insert into public.assignment_question ("assignmentId", content) values (777, 'Zhuyeping');
insert into public.assignment_question ("assignmentId", content) values (85, 'Djibo');
insert into public.assignment_question ("assignmentId", content) values (438, 'Labruge');
insert into public.assignment_question ("assignmentId", content) values (327, 'Jalālābād');
insert into public.assignment_question ("assignmentId", content) values (35, 'Bořitov');
insert into public.assignment_question ("assignmentId", content) values (670, 'Lahan Sai');
insert into public.assignment_question ("assignmentId", content) values (709, 'Obubra');
insert into public.assignment_question ("assignmentId", content) values (647, 'Tidili Mesfioua');
insert into public.assignment_question ("assignmentId", content) values (927, 'Donggaocun');
insert into public.assignment_question ("assignmentId", content) values (566, 'Klyuchevsk');
insert into public.assignment_question ("assignmentId", content) values (914, 'Putina');
insert into public.assignment_question ("assignmentId", content) values (511, 'Colegiales');
insert into public.assignment_question ("assignmentId", content) values (916, 'Pejë');
insert into public.assignment_question ("assignmentId", content) values (555, 'Alangalang');
insert into public.assignment_question ("assignmentId", content) values (723, 'Pemba');
insert into public.assignment_question ("assignmentId", content) values (187, 'Jam');
insert into public.assignment_question ("assignmentId", content) values (258, 'Bagrāmī');
insert into public.assignment_question ("assignmentId", content) values (399, 'Zhanlong');
insert into public.assignment_question ("assignmentId", content) values (562, 'Rio Claro');
insert into public.assignment_question ("assignmentId", content) values (669, 'Almolonga');
insert into public.assignment_question ("assignmentId", content) values (392, 'El Benque');
insert into public.assignment_question ("assignmentId", content) values (420, 'Itapicuru');
insert into public.assignment_question ("assignmentId", content) values (518, 'Béthune');
insert into public.assignment_question ("assignmentId", content) values (336, 'Ureshino');
insert into public.assignment_question ("assignmentId", content) values (998, 'Beddeng');
insert into public.assignment_question ("assignmentId", content) values (243, 'Jiangchuanlu');
insert into public.assignment_question ("assignmentId", content) values (671, 'Zaliznychne');
insert into public.assignment_question ("assignmentId", content) values (545, 'Junliangcheng');
insert into public.assignment_question ("assignmentId", content) values (97, 'Medvedevo');
insert into public.assignment_question ("assignmentId", content) values (997, 'Palhoça');
insert into public.assignment_question ("assignmentId", content) values (603, 'Urus-Martan');
insert into public.assignment_question ("assignmentId", content) values (716, 'Songjiang');
insert into public.assignment_question ("assignmentId", content) values (467, 'Yongning');
insert into public.assignment_question ("assignmentId", content) values (294, 'Sukoreno');
insert into public.assignment_question ("assignmentId", content) values (675, 'Atiquizaya');
insert into public.assignment_question ("assignmentId", content) values (811, 'Janaka');
insert into public.assignment_question ("assignmentId", content) values (640, 'Villa Carlos Paz');
insert into public.assignment_question ("assignmentId", content) values (102, 'Dongmazar');
insert into public.assignment_question ("assignmentId", content) values (174, 'Bilopillya');
insert into public.assignment_question ("assignmentId", content) values (713, 'Sacsamarca');
insert into public.assignment_question ("assignmentId", content) values (719, 'Bergen');
insert into public.assignment_question ("assignmentId", content) values (873, 'Ndélé');
insert into public.assignment_question ("assignmentId", content) values (846, 'Huangqiang');
insert into public.assignment_question ("assignmentId", content) values (686, 'Shishi');
insert into public.assignment_question ("assignmentId", content) values (278, 'Lanchkhuti');
insert into public.assignment_question ("assignmentId", content) values (912, 'Üydzen');
insert into public.assignment_question ("assignmentId", content) values (731, 'Huangshan');
insert into public.assignment_question ("assignmentId", content) values (54, 'Pentecoste');
insert into public.assignment_question ("assignmentId", content) values (151, 'Yinhe');
insert into public.assignment_question ("assignmentId", content) values (399, 'Kawengan');
insert into public.assignment_question ("assignmentId", content) values (117, 'Xiongchi');
insert into public.assignment_question ("assignmentId", content) values (878, 'Ribeirão Pires');
insert into public.assignment_question ("assignmentId", content) values (127, 'Wuda');
insert into public.assignment_question ("assignmentId", content) values (165, 'Rio Meão');
insert into public.assignment_question ("assignmentId", content) values (675, 'La Tigra');
insert into public.assignment_question ("assignmentId", content) values (508, 'Osorno');
insert into public.assignment_question ("assignmentId", content) values (249, 'Novoshakhtinsk');
insert into public.assignment_question ("assignmentId", content) values (855, 'Desa Werasari');
insert into public.assignment_question ("assignmentId", content) values (702, 'Panenjoan');
insert into public.assignment_question ("assignmentId", content) values (65, 'San Julian');
insert into public.assignment_question ("assignmentId", content) values (318, 'Angkahgede');
insert into public.assignment_question ("assignmentId", content) values (366, 'Bagong Pagasa');
insert into public.assignment_question ("assignmentId", content) values (785, 'Medenine');
insert into public.assignment_question ("assignmentId", content) values (870, 'Kyurdarmir');
insert into public.assignment_question ("assignmentId", content) values (788, 'Chão');
insert into public.assignment_question ("assignmentId", content) values (482, 'Kuala Lumpur');
insert into public.assignment_question ("assignmentId", content) values (456, 'Changxi');
insert into public.assignment_question ("assignmentId", content) values (966, 'Situsari');
insert into public.assignment_question ("assignmentId", content) values (722, 'Graneros');
insert into public.assignment_question ("assignmentId", content) values (734, 'Velké Meziříčí');
insert into public.assignment_question ("assignmentId", content) values (683, 'Barão de Cocais');
insert into public.assignment_question ("assignmentId", content) values (57, 'Narong');
insert into public.assignment_question ("assignmentId", content) values (509, 'Limoeiro');
insert into public.assignment_question ("assignmentId", content) values (709, 'Libu');
insert into public.assignment_question ("assignmentId", content) values (200, 'Ravānsar');
insert into public.assignment_question ("assignmentId", content) values (22, 'Huangxi');
insert into public.assignment_question ("assignmentId", content) values (624, 'Skore');
insert into public.assignment_question ("assignmentId", content) values (143, 'Bumpe');
insert into public.assignment_question ("assignmentId", content) values (931, 'Tuchola');
insert into public.assignment_question ("assignmentId", content) values (536, 'Turtas');
insert into public.assignment_question ("assignmentId", content) values (20, 'San Francisco');
insert into public.assignment_question ("assignmentId", content) values (412, 'Svalöv');
insert into public.assignment_question ("assignmentId", content) values (338, 'Ananindeua');
insert into public.assignment_question ("assignmentId", content) values (941, 'Vysotsk');
insert into public.assignment_question ("assignmentId", content) values (50, 'Al Qanāţir al Khayrīyah');
insert into public.assignment_question ("assignmentId", content) values (392, 'Songwon');
insert into public.assignment_question ("assignmentId", content) values (652, 'Laleng');
insert into public.assignment_question ("assignmentId", content) values (884, 'Narail');
insert into public.assignment_question ("assignmentId", content) values (204, 'Khvalynsk');
insert into public.assignment_question ("assignmentId", content) values (213, 'Vukojevci');
insert into public.assignment_question ("assignmentId", content) values (322, 'Lipu');
insert into public.assignment_question ("assignmentId", content) values (855, 'Hadayang');
insert into public.assignment_question ("assignmentId", content) values (872, 'Vidovci');
insert into public.assignment_question ("assignmentId", content) values (882, 'Shilovo');
insert into public.assignment_question ("assignmentId", content) values (241, 'Tianguá');
insert into public.assignment_question ("assignmentId", content) values (838, 'Schirmeck');
insert into public.assignment_question ("assignmentId", content) values (797, 'Kälviä');
insert into public.assignment_question ("assignmentId", content) values (177, 'Smara');
insert into public.assignment_question ("assignmentId", content) values (681, 'Kallífytos');
insert into public.assignment_question ("assignmentId", content) values (354, 'Tungelsta');
insert into public.assignment_question ("assignmentId", content) values (53, 'Kerek');
insert into public.assignment_question ("assignmentId", content) values (889, 'Sepahua');
insert into public.assignment_question ("assignmentId", content) values (970, 'Central');
insert into public.assignment_question ("assignmentId", content) values (709, 'Kekeran');
insert into public.assignment_question ("assignmentId", content) values (129, 'Santa Valha');
insert into public.assignment_question ("assignmentId", content) values (23, 'Mandal');
insert into public.assignment_question ("assignmentId", content) values (496, 'Kaeng Khro');
insert into public.assignment_question ("assignmentId", content) values (341, 'Avellaneda');
insert into public.assignment_question ("assignmentId", content) values (718, 'Pedrogão');
insert into public.assignment_question ("assignmentId", content) values (591, 'Tianxingchang');
insert into public.assignment_question ("assignmentId", content) values (408, 'Magang');
insert into public.assignment_question ("assignmentId", content) values (993, 'Farmahīn');
insert into public.assignment_question ("assignmentId", content) values (586, 'Veranópolis');
insert into public.assignment_question ("assignmentId", content) values (21, 'Al Qadarif');
insert into public.assignment_question ("assignmentId", content) values (71, 'Bełżyce');
insert into public.assignment_question ("assignmentId", content) values (210, 'Mathakola');
insert into public.assignment_question ("assignmentId", content) values (580, 'Bidbid');
insert into public.assignment_question ("assignmentId", content) values (366, 'Lokwabe');
insert into public.assignment_question ("assignmentId", content) values (668, 'Zongga');
insert into public.assignment_question ("assignmentId", content) values (832, 'Andekantor');
insert into public.assignment_question ("assignmentId", content) values (708, 'Dębowa Łąka');
insert into public.assignment_question ("assignmentId", content) values (107, 'Vykhino-Zhulebino');
insert into public.assignment_question ("assignmentId", content) values (766, 'København');
insert into public.assignment_question ("assignmentId", content) values (606, 'Kuala Lumpur');
insert into public.assignment_question ("assignmentId", content) values (783, 'Rocky Mountain House');
insert into public.assignment_question ("assignmentId", content) values (50, 'Zabłocie');
insert into public.assignment_question ("assignmentId", content) values (310, 'Burnham');
insert into public.assignment_question ("assignmentId", content) values (581, 'Boguchar');
insert into public.assignment_question ("assignmentId", content) values (575, 'Severobaykal’sk');
insert into public.assignment_question ("assignmentId", content) values (768, 'Bebandem');
insert into public.assignment_question ("assignmentId", content) values (924, 'Donegal');
insert into public.assignment_question ("assignmentId", content) values (396, 'Uyuni');
insert into public.assignment_question ("assignmentId", content) values (614, 'Chancay');
insert into public.assignment_question ("assignmentId", content) values (278, 'Thākurgaon');
insert into public.assignment_question ("assignmentId", content) values (900, 'Gävle');
insert into public.assignment_question ("assignmentId", content) values (325, 'Schiedam postbusnummers');
insert into public.assignment_question ("assignmentId", content) values (912, 'Pregradnaya');
insert into public.assignment_question ("assignmentId", content) values (14, 'Västerås');
insert into public.assignment_question ("assignmentId", content) values (31, 'Shuangfeng');
insert into public.assignment_question ("assignmentId", content) values (995, 'Tejar');
insert into public.assignment_question ("assignmentId", content) values (880, 'Verin Dvin');
insert into public.assignment_question ("assignmentId", content) values (546, 'Barrouallie');
insert into public.assignment_question ("assignmentId", content) values (6, 'Novoukrainskiy');
insert into public.assignment_question ("assignmentId", content) values (248, 'Beichengqu');
insert into public.assignment_question ("assignmentId", content) values (713, 'Sadov');
insert into public.assignment_question ("assignmentId", content) values (14, 'Wang Noi');
insert into public.assignment_question ("assignmentId", content) values (489, 'Ostrów Wielkopolski');
insert into public.assignment_question ("assignmentId", content) values (56, 'Galis');
insert into public.assignment_question ("assignmentId", content) values (941, 'Kanye');
insert into public.assignment_question ("assignmentId", content) values (872, 'Kladruby');
insert into public.assignment_question ("assignmentId", content) values (824, 'Pittsburgh');
insert into public.assignment_question ("assignmentId", content) values (359, 'Dawung');
insert into public.assignment_question ("assignmentId", content) values (641, 'Kasama');
insert into public.assignment_question ("assignmentId", content) values (306, 'Changyuan');
insert into public.assignment_question ("assignmentId", content) values (269, 'Jinggongqiao');
insert into public.assignment_question ("assignmentId", content) values (836, 'Ubinskoye');
insert into public.assignment_question ("assignmentId", content) values (969, 'Talodi');
insert into public.assignment_question ("assignmentId", content) values (343, 'Xiangcheng');
insert into public.assignment_question ("assignmentId", content) values (208, 'Stírion');
insert into public.assignment_question ("assignmentId", content) values (299, 'Desakolot');
insert into public.assignment_question ("assignmentId", content) values (432, 'Klau');
insert into public.assignment_question ("assignmentId", content) values (174, 'Jankovec');
insert into public.assignment_question ("assignmentId", content) values (636, 'Bailingnao');
insert into public.assignment_question ("assignmentId", content) values (273, 'Faaone');
insert into public.assignment_question ("assignmentId", content) values (176, 'Yafan');
insert into public.assignment_question ("assignmentId", content) values (871, 'Airmadidi');
insert into public.assignment_question ("assignmentId", content) values (386, 'Gorskaya');
insert into public.assignment_question ("assignmentId", content) values (732, 'Kowŏn-ŭp');
insert into public.assignment_question ("assignmentId", content) values (302, 'Göteborg');
insert into public.assignment_question ("assignmentId", content) values (137, 'Ngawen');
insert into public.assignment_question ("assignmentId", content) values (685, 'Sieroszewice');
insert into public.assignment_question ("assignmentId", content) values (371, 'Pescara');
insert into public.assignment_question ("assignmentId", content) values (381, 'Oświęcim');
insert into public.assignment_question ("assignmentId", content) values (851, 'Azinhal');
insert into public.assignment_question ("assignmentId", content) values (120, 'Lela');
insert into public.assignment_question ("assignmentId", content) values (103, 'Cabay');
insert into public.assignment_question ("assignmentId", content) values (103, 'Rosebank');
insert into public.assignment_question ("assignmentId", content) values (706, 'Ciénaga');
insert into public.assignment_question ("assignmentId", content) values (207, 'Zhuravka');
insert into public.assignment_question ("assignmentId", content) values (959, 'Cienfuegos');
insert into public.assignment_question ("assignmentId", content) values (397, 'Santa Cruz');
insert into public.assignment_question ("assignmentId", content) values (652, 'Yunshan');
insert into public.assignment_question ("assignmentId", content) values (924, 'Si Prachan');
insert into public.assignment_question ("assignmentId", content) values (489, 'Brnaze');
insert into public.assignment_question ("assignmentId", content) values (16, 'Sojo');
insert into public.assignment_question ("assignmentId", content) values (376, 'Balaogan');
insert into public.assignment_question ("assignmentId", content) values (104, 'Kleszczewo');
insert into public.assignment_question ("assignmentId", content) values (765, 'Lazaro Cardenas');
insert into public.assignment_question ("assignmentId", content) values (820, 'Flushing');
insert into public.assignment_question ("assignmentId", content) values (955, 'Guarenas');
insert into public.assignment_question ("assignmentId", content) values (777, 'Gryaznovskoye');
insert into public.assignment_question ("assignmentId", content) values (810, 'Figueira dos Cavaleiros');
insert into public.assignment_question ("assignmentId", content) values (502, 'Jinbi');
insert into public.assignment_question ("assignmentId", content) values (814, 'Butahai');
insert into public.assignment_question ("assignmentId", content) values (700, 'Chaka');
insert into public.assignment_question ("assignmentId", content) values (984, 'Novoorsk');
insert into public.assignment_question ("assignmentId", content) values (167, 'Ncue');
insert into public.assignment_question ("assignmentId", content) values (425, 'Geneng');
insert into public.assignment_question ("assignmentId", content) values (755, 'Dowlatyār');
insert into public.assignment_question ("assignmentId", content) values (237, 'Datang');
insert into public.assignment_question ("assignmentId", content) values (259, 'Jinfeng');
insert into public.assignment_question ("assignmentId", content) values (344, 'Klyuchi');
insert into public.assignment_question ("assignmentId", content) values (534, 'Tongshan');
insert into public.assignment_question ("assignmentId", content) values (799, 'Nurota Shahri');
insert into public.assignment_question ("assignmentId", content) values (743, 'Shilipu');
insert into public.assignment_question ("assignmentId", content) values (982, 'Oakland');
insert into public.assignment_question ("assignmentId", content) values (477, 'Muskegon');
insert into public.assignment_question ("assignmentId", content) values (718, 'Makiwalo');
insert into public.assignment_question ("assignmentId", content) values (336, 'Šoštanj');
insert into public.assignment_question ("assignmentId", content) values (542, 'Domont');
insert into public.assignment_question ("assignmentId", content) values (179, 'Colmar');
insert into public.assignment_question ("assignmentId", content) values (965, 'General Arenales');
insert into public.assignment_question ("assignmentId", content) values (643, 'Bukowiec');
insert into public.assignment_question ("assignmentId", content) values (981, 'Samir');
insert into public.assignment_question ("assignmentId", content) values (159, 'Pires do Rio');
insert into public.assignment_question ("assignmentId", content) values (479, 'La Broquerie');
insert into public.assignment_question ("assignmentId", content) values (689, 'Sfax');
insert into public.assignment_question ("assignmentId", content) values (431, 'Fuente de Oro');
insert into public.assignment_question ("assignmentId", content) values (484, 'Óbidos');
insert into public.assignment_question ("assignmentId", content) values (876, 'Rozivka');
insert into public.assignment_question ("assignmentId", content) values (311, 'Rungkam');
insert into public.assignment_question ("assignmentId", content) values (640, 'Espinal');
insert into public.assignment_question ("assignmentId", content) values (619, 'Yangzi');
insert into public.assignment_question ("assignmentId", content) values (517, 'Laascaanood');
insert into public.assignment_question ("assignmentId", content) values (418, 'Komsomolsk');
insert into public.assignment_question ("assignmentId", content) values (409, 'Banjar Medura');
insert into public.assignment_question ("assignmentId", content) values (373, 'Ksawerów');
insert into public.assignment_question ("assignmentId", content) values (857, 'Al Aḩmadī');
insert into public.assignment_question ("assignmentId", content) values (759, 'Xiaotao');
insert into public.assignment_question ("assignmentId", content) values (531, 'Gali');
insert into public.assignment_question ("assignmentId", content) values (205, 'Anxi');
insert into public.assignment_question ("assignmentId", content) values (46, 'Djibouti');
insert into public.assignment_question ("assignmentId", content) values (280, 'Kaz');
insert into public.assignment_question ("assignmentId", content) values (480, 'Arinos');
insert into public.assignment_question ("assignmentId", content) values (774, 'Kotanopan');
insert into public.assignment_question ("assignmentId", content) values (184, 'Chapayeve');
insert into public.assignment_question ("assignmentId", content) values (990, 'Saint-Quentin-en-Yvelines');
insert into public.assignment_question ("assignmentId", content) values (338, 'Uinskoye');
insert into public.assignment_question ("assignmentId", content) values (380, 'Jaú');
insert into public.assignment_question ("assignmentId", content) values (889, 'Baolong');
insert into public.assignment_question ("assignmentId", content) values (957, 'Springfield');
insert into public.assignment_question ("assignmentId", content) values (541, 'Gaotian');
insert into public.assignment_question ("assignmentId", content) values (715, 'Mwembe');
insert into public.assignment_question ("assignmentId", content) values (299, 'Крушево');
insert into public.assignment_question ("assignmentId", content) values (68, 'Petrodvorets');
insert into public.assignment_question ("assignmentId", content) values (675, 'Otllak');
insert into public.assignment_question ("assignmentId", content) values (247, 'Motomiya');
insert into public.assignment_question ("assignmentId", content) values (498, 'Il’ya');
insert into public.assignment_question ("assignmentId", content) values (174, 'Wang Nam Yen');
insert into public.assignment_question ("assignmentId", content) values (202, 'Kalān Deh');
insert into public.assignment_question ("assignmentId", content) values (668, 'Fushëkuqe');
insert into public.assignment_question ("assignmentId", content) values (800, 'Maguwon');
insert into public.assignment_question ("assignmentId", content) values (123, 'Bukowina Tatrzańska');
insert into public.assignment_question ("assignmentId", content) values (527, 'Kabo');
insert into public.assignment_question ("assignmentId", content) values (90, 'Massenya');
insert into public.assignment_question ("assignmentId", content) values (565, 'Thai Charoen');
insert into public.assignment_question ("assignmentId", content) values (399, 'Kriel');
insert into public.assignment_question ("assignmentId", content) values (100, 'Wanglinkou');
insert into public.assignment_question ("assignmentId", content) values (740, 'Ylihärmä');
insert into public.assignment_question ("assignmentId", content) values (253, 'Santa Maria Oliveira');
insert into public.assignment_question ("assignmentId", content) values (315, 'Kentville');
insert into public.assignment_question ("assignmentId", content) values (545, 'Cadiz');
insert into public.assignment_question ("assignmentId", content) values (711, 'Tizgane');
insert into public.assignment_question ("assignmentId", content) values (596, 'Itsandzéni');
insert into public.assignment_question ("assignmentId", content) values (974, 'Rusocice');
insert into public.assignment_question ("assignmentId", content) values (368, 'Žemaičių Naumiestis');
insert into public.assignment_question ("assignmentId", content) values (251, 'Křižanov');
insert into public.assignment_question ("assignmentId", content) values (832, 'Gostovići');
insert into public.assignment_question ("assignmentId", content) values (4, 'Pattani');
insert into public.assignment_question ("assignmentId", content) values (720, 'Vermelha');
insert into public.assignment_question ("assignmentId", content) values (798, 'Yihe');
insert into public.assignment_question ("assignmentId", content) values (625, 'Stockholm');
insert into public.assignment_question ("assignmentId", content) values (115, 'Bu‘eina');
insert into public.assignment_question ("assignmentId", content) values (646, 'Jovellanos');
insert into public.assignment_question ("assignmentId", content) values (388, 'Allanridge');
insert into public.assignment_question ("assignmentId", content) values (890, 'Guiyang');
insert into public.assignment_question ("assignmentId", content) values (618, 'Randu');
insert into public.assignment_question ("assignmentId", content) values (114, 'Águia Branca');
insert into public.assignment_question ("assignmentId", content) values (174, 'Goianira');
insert into public.assignment_question ("assignmentId", content) values (105, 'Zaragoza');
insert into public.assignment_question ("assignmentId", content) values (165, 'Villefontaine');
insert into public.assignment_question ("assignmentId", content) values (890, 'Limoeiro do Ajuru');
insert into public.assignment_question ("assignmentId", content) values (452, 'Austin');
insert into public.assignment_question ("assignmentId", content) values (496, 'København');
insert into public.assignment_question ("assignmentId", content) values (579, 'Cockburn Town');
insert into public.assignment_question ("assignmentId", content) values (921, 'Zhushan');
insert into public.assignment_question ("assignmentId", content) values (549, 'Rennes');
insert into public.assignment_question ("assignmentId", content) values (139, 'Pedra Azul');
insert into public.assignment_question ("assignmentId", content) values (400, 'Västanfjärd');
insert into public.assignment_question ("assignmentId", content) values (737, 'Hobonio');
insert into public.assignment_question ("assignmentId", content) values (368, 'Hoi');
insert into public.assignment_question ("assignmentId", content) values (21, 'Picos');
insert into public.assignment_question ("assignmentId", content) values (754, 'Dois Portos');
insert into public.assignment_question ("assignmentId", content) values (220, 'Libertador General San Martín');
insert into public.assignment_question ("assignmentId", content) values (622, 'Maymana');
insert into public.assignment_question ("assignmentId", content) values (904, 'Tilik');
insert into public.assignment_question ("assignmentId", content) values (317, 'As Suwaydā’');
insert into public.assignment_question ("assignmentId", content) values (353, 'Bečej');
insert into public.assignment_question ("assignmentId", content) values (99, 'Nyandoma');
insert into public.assignment_question ("assignmentId", content) values (640, 'Balahovit');
insert into public.assignment_question ("assignmentId", content) values (171, 'Xiahong');
insert into public.assignment_question ("assignmentId", content) values (256, 'Liuzhuang');
insert into public.assignment_question ("assignmentId", content) values (150, 'Alca');
insert into public.assignment_question ("assignmentId", content) values (476, 'Ulaan-Ereg');
insert into public.assignment_question ("assignmentId", content) values (193, 'Cincinnati');
insert into public.assignment_question ("assignmentId", content) values (986, 'Syanno');
insert into public.assignment_question ("assignmentId", content) values (333, 'Shangcai Zhongxing');
insert into public.assignment_question ("assignmentId", content) values (356, 'Tobatí');
insert into public.assignment_question ("assignmentId", content) values (867, 'Majagual');
insert into public.assignment_question ("assignmentId", content) values (928, 'Vysokovsk');
insert into public.assignment_question ("assignmentId", content) values (920, 'Limoges');
insert into public.assignment_question ("assignmentId", content) values (730, 'Huanglong');
insert into public.assignment_question ("assignmentId", content) values (837, 'Gushui');
insert into public.assignment_question ("assignmentId", content) values (867, 'Ballisodare');
insert into public.assignment_question ("assignmentId", content) values (884, 'Xikou');
insert into public.assignment_question ("assignmentId", content) values (337, 'Valbo');
insert into public.assignment_question ("assignmentId", content) values (812, 'Nanyulinxi');
insert into public.assignment_question ("assignmentId", content) values (235, 'Blagoveshchenka');
insert into public.assignment_question ("assignmentId", content) values (486, 'Puerto Boyacá');
insert into public.assignment_question ("assignmentId", content) values (803, 'Sa‘sa‘');
insert into public.assignment_question ("assignmentId", content) values (764, 'Sadská');
insert into public.assignment_question ("assignmentId", content) values (372, 'Huaranchal');
insert into public.assignment_question ("assignmentId", content) values (560, 'Pumaqangtang');
insert into public.assignment_question ("assignmentId", content) values (358, 'Ciangir');
insert into public.assignment_question ("assignmentId", content) values (660, 'Sơn Tây');
insert into public.assignment_question ("assignmentId", content) values (938, 'Benito Juarez');
insert into public.assignment_question ("assignmentId", content) values (631, 'Qibu');
insert into public.assignment_question ("assignmentId", content) values (390, 'Pöytyä');
insert into public.assignment_question ("assignmentId", content) values (649, 'Póvoa');
insert into public.assignment_question ("assignmentId", content) values (403, 'Vatutino');
insert into public.assignment_question ("assignmentId", content) values (791, 'Fagersta');
insert into public.assignment_question ("assignmentId", content) values (282, 'Bureya');
insert into public.assignment_question ("assignmentId", content) values (489, 'Sechenovo');
insert into public.assignment_question ("assignmentId", content) values (231, 'Croix');
insert into public.assignment_question ("assignmentId", content) values (65, 'Guisguis');
insert into public.assignment_question ("assignmentId", content) values (556, 'Huoshaodian');
insert into public.assignment_question ("assignmentId", content) values (189, 'Rongwo');
insert into public.assignment_question ("assignmentId", content) values (263, 'Pingqiao');
insert into public.assignment_question ("assignmentId", content) values (836, 'Florentino Ameghino');
insert into public.assignment_question ("assignmentId", content) values (89, 'Embalse');
insert into public.assignment_question ("assignmentId", content) values (837, 'Farasān');
insert into public.assignment_question ("assignmentId", content) values (986, 'Saransk');
insert into public.assignment_question ("assignmentId", content) values (393, 'Pingtan');
insert into public.assignment_question ("assignmentId", content) values (583, 'Xiashitai');
insert into public.assignment_question ("assignmentId", content) values (939, 'Beidao');
insert into public.assignment_question ("assignmentId", content) values (736, 'Bang Nam Priao');
insert into public.assignment_question ("assignmentId", content) values (314, 'Kalajoki');
insert into public.assignment_question ("assignmentId", content) values (801, 'Skópelos');
insert into public.assignment_question ("assignmentId", content) values (693, 'Karangwaru');
insert into public.assignment_question ("assignmentId", content) values (501, 'Dulles');
insert into public.assignment_question ("assignmentId", content) values (356, 'Nurota Shahri');
insert into public.assignment_question ("assignmentId", content) values (805, 'Lukavice');
insert into public.assignment_question ("assignmentId", content) values (923, 'Banaybanay');
insert into public.assignment_question ("assignmentId", content) values (837, 'Quiches');
insert into public.assignment_question ("assignmentId", content) values (987, 'San Miguel del Padrón');
insert into public.assignment_question ("assignmentId", content) values (69, 'Canala');
insert into public.assignment_question ("assignmentId", content) values (907, 'Shang Boingor');
insert into public.assignment_question ("assignmentId", content) values (807, 'Sabi');
insert into public.assignment_question ("assignmentId", content) values (666, 'Lieksa');
insert into public.assignment_question ("assignmentId", content) values (963, 'Xinning');
insert into public.assignment_question ("assignmentId", content) values (674, 'Donetsk');
insert into public.assignment_question ("assignmentId", content) values (679, 'Huazhu');
insert into public.assignment_question ("assignmentId", content) values (347, 'Grijó');
insert into public.assignment_question ("assignmentId", content) values (404, 'Nidek');
insert into public.assignment_question ("assignmentId", content) values (255, 'Huangbizhuang');
insert into public.assignment_question ("assignmentId", content) values (580, 'Starobelokurikha');
insert into public.assignment_question ("assignmentId", content) values (61, 'Nizhniy Novgorod');
insert into public.assignment_question ("assignmentId", content) values (323, 'Lubumbashi');
insert into public.assignment_question ("assignmentId", content) values (539, 'Izbicko');
insert into public.assignment_question ("assignmentId", content) values (502, 'Mancos');
insert into public.assignment_question ("assignmentId", content) values (339, 'Guadalupe');
insert into public.assignment_question ("assignmentId", content) values (554, 'Janowiec');
insert into public.assignment_question ("assignmentId", content) values (817, 'Sophia Antipolis');
insert into public.assignment_question ("assignmentId", content) values (682, 'Kugri');
insert into public.assignment_question ("assignmentId", content) values (171, 'Caacupé');
insert into public.assignment_question ("assignmentId", content) values (810, 'Xiaojie');
insert into public.assignment_question ("assignmentId", content) values (141, 'Mataloko');
insert into public.assignment_question ("assignmentId", content) values (917, 'Zhukovo');
insert into public.assignment_question ("assignmentId", content) values (55, 'Saint-Malo');
insert into public.assignment_question ("assignmentId", content) values (55, 'Gonzalo Pizarro');
insert into public.assignment_question ("assignmentId", content) values (970, 'Palma Gil');
insert into public.assignment_question ("assignmentId", content) values (568, 'Carvalhal');
insert into public.assignment_question ("assignmentId", content) values (166, 'Tōkamachi');
insert into public.assignment_question ("assignmentId", content) values (377, 'Goúrnes');
insert into public.assignment_question ("assignmentId", content) values (498, 'Tsul-Ulaan');
insert into public.assignment_question ("assignmentId", content) values (246, 'Joaquín V. González');
insert into public.assignment_question ("assignmentId", content) values (497, 'Lunel');
insert into public.assignment_question ("assignmentId", content) values (647, 'Gustavia');
insert into public.assignment_question ("assignmentId", content) values (863, 'Nakhon Pathom');
insert into public.assignment_question ("assignmentId", content) values (808, 'Tiraspol');
insert into public.assignment_question ("assignmentId", content) values (848, 'Yuqi');
insert into public.assignment_question ("assignmentId", content) values (690, 'Cibatuireng');
insert into public.assignment_question ("assignmentId", content) values (253, 'Laholm');
insert into public.assignment_question ("assignmentId", content) values (250, 'Cuauhtemoc');
insert into public.assignment_question ("assignmentId", content) values (886, 'Sanxi');
insert into public.assignment_question ("assignmentId", content) values (219, 'Na Chueak');
insert into public.assignment_question ("assignmentId", content) values (179, 'Lhakangtang');
insert into public.assignment_question ("assignmentId", content) values (526, 'Tonglin');
insert into public.assignment_question ("assignmentId", content) values (174, 'Redcliff');
insert into public.assignment_question ("assignmentId", content) values (694, 'Rakitovo');
insert into public.assignment_question ("assignmentId", content) values (843, 'Chai Badan');
insert into public.assignment_question ("assignmentId", content) values (241, 'Alegre');
insert into public.assignment_question ("assignmentId", content) values (906, 'Feondari');
insert into public.assignment_question ("assignmentId", content) values (304, 'Baracatan');
insert into public.assignment_question ("assignmentId", content) values (648, 'Burūm');
insert into public.assignment_question ("assignmentId", content) values (679, 'Cankova');
insert into public.assignment_question ("assignmentId", content) values (43, 'Bakovci');
insert into public.assignment_question ("assignmentId", content) values (917, 'Touguinha');
insert into public.assignment_question ("assignmentId", content) values (61, 'Curuzú Cuatiá');
insert into public.assignment_question ("assignmentId", content) values (305, 'Batas Barat');
insert into public.assignment_question ("assignmentId", content) values (800, 'Clodomira');
insert into public.assignment_question ("assignmentId", content) values (701, 'Taradale');
insert into public.assignment_question ("assignmentId", content) values (285, 'Noebesa');
insert into public.assignment_question ("assignmentId", content) values (652, 'Šid');
insert into public.assignment_question ("assignmentId", content) values (398, 'Xintang');
insert into public.assignment_question ("assignmentId", content) values (304, 'Karantaba');
insert into public.assignment_question ("assignmentId", content) values (884, 'Herīs');
insert into public.assignment_question ("assignmentId", content) values (820, 'Cimo de Vila');
insert into public.assignment_question ("assignmentId", content) values (600, 'Jingkou');
insert into public.assignment_question ("assignmentId", content) values (140, 'Konārak');
insert into public.assignment_question ("assignmentId", content) values (166, 'Xinjia');
insert into public.assignment_question ("assignmentId", content) values (83, 'La Calera');
insert into public.assignment_question ("assignmentId", content) values (152, 'Lalig');
insert into public.assignment_question ("assignmentId", content) values (338, 'Dresden');
insert into public.assignment_question ("assignmentId", content) values (910, 'Babantar');
insert into public.assignment_question ("assignmentId", content) values (979, 'Lavaltrie');
insert into public.assignment_question ("assignmentId", content) values (562, 'Baizhang');
insert into public.assignment_question ("assignmentId", content) values (103, 'Maimará');
insert into public.assignment_question ("assignmentId", content) values (110, 'Kumo');
insert into public.assignment_question ("assignmentId", content) values (360, 'Ceres');
insert into public.assignment_question ("assignmentId", content) values (368, 'Äänekoski');
insert into public.assignment_question ("assignmentId", content) values (942, 'Bieligutai');
insert into public.assignment_question ("assignmentId", content) values (514, 'Ikongo');
insert into public.assignment_question ("assignmentId", content) values (339, 'Santa Rosa');
insert into public.assignment_question ("assignmentId", content) values (162, 'Colombes');
insert into public.assignment_question ("assignmentId", content) values (764, 'Nanqiu');
insert into public.assignment_question ("assignmentId", content) values (812, 'Pueblo Nuevo');
insert into public.assignment_question ("assignmentId", content) values (76, 'Nijiangping');
insert into public.assignment_question ("assignmentId", content) values (296, 'Neuilly-sur-Marne');
insert into public.assignment_question ("assignmentId", content) values (450, 'Pasirpanjang');
insert into public.assignment_question ("assignmentId", content) values (606, 'Novocheboksarsk');
insert into public.assignment_question ("assignmentId", content) values (881, 'Linoan');
insert into public.assignment_question ("assignmentId", content) values (896, 'Dazhou');
insert into public.assignment_question ("assignmentId", content) values (578, 'Yangjingziwan');
insert into public.assignment_question ("assignmentId", content) values (796, 'Loreto');
insert into public.assignment_question ("assignmentId", content) values (703, 'Täby');
insert into public.assignment_question ("assignmentId", content) values (929, 'Niedrzwica Duża');
insert into public.assignment_question ("assignmentId", content) values (368, 'Keroak');
insert into public.assignment_question ("assignmentId", content) values (302, 'Tiyingtali Kelod');
insert into public.assignment_question ("assignmentId", content) values (440, 'Antalaha');
insert into public.assignment_question ("assignmentId", content) values (543, 'Dos Quebradas');
insert into public.assignment_question ("assignmentId", content) values (532, 'Aricapampa');
insert into public.assignment_question ("assignmentId", content) values (986, 'Palopo');
insert into public.assignment_question ("assignmentId", content) values (492, 'Vitória do Mearim');
insert into public.assignment_question ("assignmentId", content) values (413, 'Malindi');
insert into public.assignment_question ("assignmentId", content) values (157, 'Hồ Xá');
insert into public.assignment_question ("assignmentId", content) values (359, 'Pipa');
insert into public.assignment_question ("assignmentId", content) values (505, 'Corquín');
insert into public.assignment_question ("assignmentId", content) values (386, 'Dzhubga');
insert into public.assignment_question ("assignmentId", content) values (479, 'Sundsvall');
insert into public.assignment_question ("assignmentId", content) values (820, 'Jasaan');
insert into public.assignment_question ("assignmentId", content) values (553, 'Hässleholm');
insert into public.assignment_question ("assignmentId", content) values (722, 'Duboka');
insert into public.assignment_question ("assignmentId", content) values (945, 'Lakkha Nëvre');
insert into public.assignment_question ("assignmentId", content) values (692, 'Itapira');
insert into public.assignment_question ("assignmentId", content) values (321, 'Santo Amaro');
insert into public.assignment_question ("assignmentId", content) values (956, 'Oelaba');
insert into public.assignment_question ("assignmentId", content) values (623, 'Louis Trichardt');
insert into public.assignment_question ("assignmentId", content) values (30, 'Jerez');
insert into public.assignment_question ("assignmentId", content) values (87, 'Arras');
insert into public.assignment_question ("assignmentId", content) values (656, 'Rufino');
insert into public.assignment_question ("assignmentId", content) values (208, 'Shah Alam');
insert into public.assignment_question ("assignmentId", content) values (806, 'Ica');
insert into public.assignment_question ("assignmentId", content) values (351, 'Shanghu');
insert into public.assignment_question ("assignmentId", content) values (677, 'Krzyżanów');
insert into public.assignment_question ("assignmentId", content) values (653, 'Ivanishchi');
insert into public.assignment_question ("assignmentId", content) values (723, 'Xuân Trường');
insert into public.assignment_question ("assignmentId", content) values (161, 'Yoshkar-Ola');
insert into public.assignment_question ("assignmentId", content) values (653, 'Jambeyan');
insert into public.assignment_question ("assignmentId", content) values (309, 'Da’an');
insert into public.assignment_question ("assignmentId", content) values (458, 'Dordrecht');
insert into public.assignment_question ("assignmentId", content) values (472, 'El Estor');
insert into public.assignment_question ("assignmentId", content) values (335, 'Knjazevac');
insert into public.assignment_question ("assignmentId", content) values (118, 'Akonolinga');
insert into public.assignment_question ("assignmentId", content) values (431, 'Anling');
insert into public.assignment_question ("assignmentId", content) values (10, 'Mirimire');
insert into public.assignment_question ("assignmentId", content) values (896, 'Kliteh');
insert into public.assignment_question ("assignmentId", content) values (425, 'Chandra');
insert into public.assignment_question ("assignmentId", content) values (31, 'Ilare');
insert into public.assignment_question ("assignmentId", content) values (632, 'Kangalassy');
insert into public.assignment_question ("assignmentId", content) values (775, 'Divača');
insert into public.assignment_question ("assignmentId", content) values (321, 'Kemlya');
insert into public.assignment_question ("assignmentId", content) values (198, 'Panite');
insert into public.assignment_question ("assignmentId", content) values (688, 'Silab');
insert into public.assignment_question ("assignmentId", content) values (679, 'Yukhnov');
insert into public.assignment_question ("assignmentId", content) values (884, 'Killumney');
insert into public.assignment_question ("assignmentId", content) values (166, 'Traganón');
insert into public.assignment_question ("assignmentId", content) values (841, 'Dioknisi');
insert into public.assignment_question ("assignmentId", content) values (463, 'Novomyshastovskaya');
insert into public.assignment_question ("assignmentId", content) values (986, 'Ural');
insert into public.assignment_question ("assignmentId", content) values (935, 'New York City');
insert into public.assignment_question ("assignmentId", content) values (139, 'Gandi');
insert into public.assignment_question ("assignmentId", content) values (142, 'Jintao');
insert into public.assignment_question ("assignmentId", content) values (48, 'Savitaipale');
insert into public.assignment_question ("assignmentId", content) values (931, 'Troyes');
insert into public.assignment_question ("assignmentId", content) values (212, 'Juarez');
insert into public.assignment_question ("assignmentId", content) values (75, 'Anopog');
insert into public.assignment_question ("assignmentId", content) values (392, 'Kadusimbar');
insert into public.assignment_question ("assignmentId", content) values (882, 'Drnje');
insert into public.assignment_question ("assignmentId", content) values (71, 'Danzi');
insert into public.assignment_question ("assignmentId", content) values (392, 'Jardín América');
insert into public.assignment_question ("assignmentId", content) values (767, 'Pakis');
insert into public.assignment_question ("assignmentId", content) values (205, 'Syamzha');
insert into public.assignment_question ("assignmentId", content) values (591, 'Vale de Açores');
insert into public.assignment_question ("assignmentId", content) values (757, 'Nawal');
insert into public.assignment_question ("assignmentId", content) values (645, 'Prado Siongco');
insert into public.assignment_question ("assignmentId", content) values (646, 'Kopstal');
insert into public.assignment_question ("assignmentId", content) values (386, 'Watuweri');
insert into public.assignment_question ("assignmentId", content) values (414, 'Sulop');
insert into public.assignment_question ("assignmentId", content) values (942, 'Chư Sê');
insert into public.assignment_question ("assignmentId", content) values (190, 'Nashville');
insert into public.assignment_question ("assignmentId", content) values (829, 'Jinchuan');
insert into public.assignment_question ("assignmentId", content) values (376, 'Kangasala');
insert into public.assignment_question ("assignmentId", content) values (480, 'Tongchuan');
insert into public.assignment_question ("assignmentId", content) values (959, 'Huangge');
insert into public.assignment_question ("assignmentId", content) values (7, 'Airmolek');
insert into public.assignment_question ("assignmentId", content) values (472, 'Pag');
insert into public.assignment_question ("assignmentId", content) values (955, 'Abiko');
insert into public.assignment_question ("assignmentId", content) values (439, 'Oslo');
insert into public.assignment_question ("assignmentId", content) values (469, 'Karlshamn');
insert into public.assignment_question ("assignmentId", content) values (220, 'Pandangan Kulon');
insert into public.assignment_question ("assignmentId", content) values (622, 'Da’an');
insert into public.assignment_question ("assignmentId", content) values (511, 'Villaguay');
insert into public.assignment_question ("assignmentId", content) values (699, 'Buckland');
insert into public.assignment_question ("assignmentId", content) values (512, 'Coihaique');
insert into public.assignment_question ("assignmentId", content) values (238, 'Rive-de-Gier');
insert into public.assignment_question ("assignmentId", content) values (981, 'Eauripik');
insert into public.assignment_question ("assignmentId", content) values (381, 'Orocué');
insert into public.assignment_question ("assignmentId", content) values (976, 'Knurów');
insert into public.assignment_question ("assignmentId", content) values (901, 'Goght’');
insert into public.assignment_question ("assignmentId", content) values (753, 'Banjar Parekan');
insert into public.assignment_question ("assignmentId", content) values (371, 'Hallsberg');
insert into public.assignment_question ("assignmentId", content) values (873, 'Mysove');
insert into public.assignment_question ("assignmentId", content) values (182, 'Sayansk');
insert into public.assignment_question ("assignmentId", content) values (84, 'Baiyun');
insert into public.assignment_question ("assignmentId", content) values (617, 'Pergamino');
insert into public.assignment_question ("assignmentId", content) values (975, 'Hilotongan');
insert into public.assignment_question ("assignmentId", content) values (528, 'Severo-Zadonsk');
insert into public.assignment_question ("assignmentId", content) values (928, 'Yiwa');
insert into public.assignment_question ("assignmentId", content) values (557, 'Bo Kluea');
insert into public.assignment_question ("assignmentId", content) values (868, 'Quận Mười');
insert into public.assignment_question ("assignmentId", content) values (589, 'Chai Nat');
insert into public.assignment_question ("assignmentId", content) values (516, 'Borovlyany');
insert into public.assignment_question ("assignmentId", content) values (453, 'Shiren');
insert into public.assignment_question ("assignmentId", content) values (296, 'Sanchahe');
insert into public.assignment_question ("assignmentId", content) values (180, 'Carmen de Viboral');
insert into public.assignment_question ("assignmentId", content) values (796, 'Eindhoven');
insert into public.assignment_question ("assignmentId", content) values (806, 'Ruixi');
insert into public.assignment_question ("assignmentId", content) values (518, 'Trinidad');
insert into public.assignment_question ("assignmentId", content) values (925, 'Comandante Luis Piedra Buena');
insert into public.assignment_question ("assignmentId", content) values (286, 'Dongqu');
insert into public.assignment_question ("assignmentId", content) values (546, 'Selemadeg Kelod');
insert into public.assignment_question ("assignmentId", content) values (369, 'Sovetskoye');
insert into public.assignment_question ("assignmentId", content) values (454, 'Qiaotou');
insert into public.assignment_question ("assignmentId", content) values (419, 'Údlice');
insert into public.assignment_question ("assignmentId", content) values (697, 'Nevinnomyssk');
insert into public.assignment_question ("assignmentId", content) values (983, 'Akhaldaba');
insert into public.assignment_question ("assignmentId", content) values (54, 'Yanglin');
insert into public.assignment_question ("assignmentId", content) values (755, 'Evxinoúpolis');
insert into public.assignment_question ("assignmentId", content) values (461, 'Sinegor''ye');
insert into public.assignment_question ("assignmentId", content) values (810, 'Yaozhanzi');
insert into public.assignment_question ("assignmentId", content) values (877, 'Tongkiling');
insert into public.assignment_question ("assignmentId", content) values (210, 'La Romana');
insert into public.assignment_question ("assignmentId", content) values (156, 'Rizómilos');
insert into public.assignment_question ("assignmentId", content) values (112, 'Črenšovci');
insert into public.assignment_question ("assignmentId", content) values (503, 'Lipnica Wielka');
insert into public.assignment_question ("assignmentId", content) values (267, 'Westport');
insert into public.assignment_question ("assignmentId", content) values (99, 'La Loma');
insert into public.assignment_question ("assignmentId", content) values (166, 'Santiago de los Caballeros');
insert into public.assignment_question ("assignmentId", content) values (751, 'Kolor');
insert into public.assignment_question ("assignmentId", content) values (91, 'San Luis');
insert into public.assignment_question ("assignmentId", content) values (731, 'Czerniewice');
insert into public.assignment_question ("assignmentId", content) values (597, 'Nocaima');
insert into public.assignment_question ("assignmentId", content) values (314, 'Makbon');
insert into public.assignment_question ("assignmentId", content) values (827, 'Patrocínio');
insert into public.assignment_question ("assignmentId", content) values (88, 'Xuetian');
insert into public.assignment_question ("assignmentId", content) values (221, 'Espinosa');
insert into public.assignment_question ("assignmentId", content) values (52, 'Odiongan');
insert into public.assignment_question ("assignmentId", content) values (521, 'Wufeng');
insert into public.assignment_question ("assignmentId", content) values (584, 'Qianpai');
insert into public.assignment_question ("assignmentId", content) values (250, 'Khueang Nai');
insert into public.assignment_question ("assignmentId", content) values (578, 'Bang Pa-in');
insert into public.assignment_question ("assignmentId", content) values (212, 'Balibago');
insert into public.assignment_question ("assignmentId", content) values (433, 'Furukawa');
insert into public.assignment_question ("assignmentId", content) values (375, 'Yeghvard');
insert into public.assignment_question ("assignmentId", content) values (252, 'Chishui');
insert into public.assignment_question ("assignmentId", content) values (908, 'Dumandesa');
insert into public.assignment_question ("assignmentId", content) values (86, 'Luwan');
insert into public.assignment_question ("assignmentId", content) values (463, 'Changsu');
insert into public.assignment_question ("assignmentId", content) values (368, 'Dankama');
insert into public.assignment_question ("assignmentId", content) values (452, 'Norakert');
insert into public.assignment_question ("assignmentId", content) values (199, 'Skrzyszów');
insert into public.assignment_question ("assignmentId", content) values (710, 'Badarganj');
insert into public.assignment_question ("assignmentId", content) values (918, 'Kihniö');
insert into public.assignment_question ("assignmentId", content) values (463, 'Kotuń');
insert into public.assignment_question ("assignmentId", content) values (744, 'Nanping');
insert into public.assignment_question ("assignmentId", content) values (534, 'Vitim');
insert into public.assignment_question ("assignmentId", content) values (267, 'Neftobod');
insert into public.assignment_question ("assignmentId", content) values (841, 'Paris 01');
insert into public.assignment_question ("assignmentId", content) values (648, 'Espinillo');
insert into public.assignment_question ("assignmentId", content) values (49, 'Tanggung');
insert into public.assignment_question ("assignmentId", content) values (297, 'Mulawato');
insert into public.assignment_question ("assignmentId", content) values (32, 'Gostagayevskaya');
insert into public.assignment_question ("assignmentId", content) values (57, 'Piúma');
insert into public.assignment_question ("assignmentId", content) values (847, 'Tambir');
insert into public.assignment_question ("assignmentId", content) values (656, 'Xukou');
insert into public.assignment_question ("assignmentId", content) values (944, 'Tessaoua');
insert into public.assignment_question ("assignmentId", content) values (875, 'Valladolid');
insert into public.assignment_question ("assignmentId", content) values (89, 'Kanáli');
insert into public.assignment_question ("assignmentId", content) values (626, 'San José');
insert into public.assignment_question ("assignmentId", content) values (990, 'Huanghuai');
insert into public.assignment_question ("assignmentId", content) values (847, 'Nagoya-shi');
insert into public.assignment_question ("assignmentId", content) values (447, 'Coro');
insert into public.assignment_question ("assignmentId", content) values (313, 'Wangshi');
insert into public.assignment_question ("assignmentId", content) values (876, 'Arias');
insert into public.assignment_question ("assignmentId", content) values (843, 'Sofia');
insert into public.assignment_question ("assignmentId", content) values (655, 'Trogan Barat');
insert into public.assignment_question ("assignmentId", content) values (174, 'Opinogóra Górna');
insert into public.assignment_question ("assignmentId", content) values (77, 'El Peñol');
insert into public.assignment_question ("assignmentId", content) values (550, 'Mosopa');
insert into public.assignment_question ("assignmentId", content) values (836, 'Oro Verde');
insert into public.assignment_question ("assignmentId", content) values (529, 'Furudate');
insert into public.assignment_question ("assignmentId", content) values (47, 'Öldziyt');
insert into public.assignment_question ("assignmentId", content) values (465, 'Dobre');
insert into public.assignment_question ("assignmentId", content) values (788, 'Dahu');
insert into public.assignment_question ("assignmentId", content) values (685, 'Gaokan');
insert into public.assignment_question ("assignmentId", content) values (899, 'El Crucero');
insert into public.assignment_question ("assignmentId", content) values (91, 'Mundri');
insert into public.assignment_question ("assignmentId", content) values (247, 'Avranches');
insert into public.assignment_question ("assignmentId", content) values (450, 'Pederneiras');
insert into public.assignment_question ("assignmentId", content) values (383, 'Manuel Antonio Mesones Muro');
insert into public.assignment_question ("assignmentId", content) values (333, 'Xiushan');
insert into public.assignment_question ("assignmentId", content) values (998, 'Hongmen');
insert into public.assignment_question ("assignmentId", content) values (268, 'Washington');
insert into public.assignment_question ("assignmentId", content) values (207, 'Makoko');
insert into public.assignment_question ("assignmentId", content) values (73, 'Wonocoyo Utara');
insert into public.assignment_question ("assignmentId", content) values (977, 'Nuevo Arraiján');
insert into public.assignment_question ("assignmentId", content) values (19, 'Acli');
insert into public.assignment_question ("assignmentId", content) values (98, 'Huaqiao');
insert into public.assignment_question ("assignmentId", content) values (652, 'Liquan Chengguanzhen');
insert into public.assignment_question ("assignmentId", content) values (450, 'Sruki');
insert into public.assignment_question ("assignmentId", content) values (850, 'Casillas');
insert into public.assignment_question ("assignmentId", content) values (994, 'Ratíškovice');
insert into public.assignment_question ("assignmentId", content) values (446, 'Tuqiao');
insert into public.assignment_question ("assignmentId", content) values (27, 'Cantilan');
insert into public.assignment_question ("assignmentId", content) values (847, 'Timiryazevo');
insert into public.assignment_question ("assignmentId", content) values (4, 'La Cruz');
insert into public.assignment_question ("assignmentId", content) values (712, 'Linqu');
insert into public.assignment_question ("assignmentId", content) values (818, 'Túquerres');
insert into public.assignment_question ("assignmentId", content) values (593, 'Zhenqian');
insert into public.assignment_question ("assignmentId", content) values (622, 'Larreynaga');
insert into public.assignment_question ("assignmentId", content) values (340, 'Monte da Boavista');
insert into public.assignment_question ("assignmentId", content) values (255, 'Popovice');
insert into public.assignment_question ("assignmentId", content) values (727, 'Qiaoyi');
insert into public.assignment_question ("assignmentId", content) values (555, 'Moussoro');
insert into public.assignment_question ("assignmentId", content) values (514, 'Wyszki');
insert into public.assignment_question ("assignmentId", content) values (826, 'Satka');
insert into public.assignment_question ("assignmentId", content) values (459, 'Mežica');
insert into public.assignment_question ("assignmentId", content) values (4, 'Santo André');
insert into public.assignment_question ("assignmentId", content) values (825, 'Indramayu');
insert into public.assignment_question ("assignmentId", content) values (150, 'Delta del Tigre');
insert into public.assignment_question ("assignmentId", content) values (487, 'Vynohradiv');
insert into public.assignment_question ("assignmentId", content) values (234, 'Date');
insert into public.assignment_question ("assignmentId", content) values (179, 'Vista Hermosa');
insert into public.assignment_question ("assignmentId", content) values (104, 'Hutang');
insert into public.assignment_question ("assignmentId", content) values (642, 'Shangde');
insert into public.assignment_question ("assignmentId", content) values (237, 'Kebon');
insert into public.assignment_question ("assignmentId", content) values (266, 'Shilin');
insert into public.assignment_question ("assignmentId", content) values (31, 'Radoboj');
insert into public.assignment_question ("assignmentId", content) values (531, 'Carcassonne');
insert into public.assignment_question ("assignmentId", content) values (439, 'Chigoré');
insert into public.assignment_question ("assignmentId", content) values (397, 'Głuchów');
insert into public.assignment_question ("assignmentId", content) values (342, 'Panikihan');
insert into public.assignment_question ("assignmentId", content) values (334, 'Złocieniec');
insert into public.assignment_question ("assignmentId", content) values (422, 'Mangli');
insert into public.assignment_question ("assignmentId", content) values (757, 'Chastyye');
insert into public.assignment_question ("assignmentId", content) values (713, 'Khvalynsk');
insert into public.assignment_question ("assignmentId", content) values (931, 'Wuyang');
insert into public.assignment_question ("assignmentId", content) values (691, 'Mañazo');
insert into public.assignment_question ("assignmentId", content) values (912, 'Dadu');
insert into public.assignment_question ("assignmentId", content) values (177, 'Nevyts’ke');
insert into public.assignment_question ("assignmentId", content) values (73, 'Custódia');
insert into public.assignment_question ("assignmentId", content) values (10, 'Perreng');
insert into public.assignment_question ("assignmentId", content) values (664, 'Gueset');
insert into public.assignment_question ("assignmentId", content) values (542, 'Khlong Luang');
insert into public.assignment_question ("assignmentId", content) values (253, 'Njurunda');
insert into public.assignment_question ("assignmentId", content) values (149, 'Linda Vista');
insert into public.assignment_question ("assignmentId", content) values (748, 'Baixi');
insert into public.assignment_question ("assignmentId", content) values (270, 'Babice');
insert into public.assignment_question ("assignmentId", content) values (11, 'Pécs');
insert into public.assignment_question ("assignmentId", content) values (502, 'Xia Dawo');
insert into public.assignment_question ("assignmentId", content) values (325, 'Bila Tserkva');
insert into public.assignment_question ("assignmentId", content) values (252, 'Banyupoh');
insert into public.assignment_question ("assignmentId", content) values (326, 'Chervonohryhorivka');
insert into public.assignment_question ("assignmentId", content) values (529, 'Ipoh');
insert into public.assignment_question ("assignmentId", content) values (518, 'Dougou');
insert into public.assignment_question ("assignmentId", content) values (5, 'Sanjiao');
insert into public.assignment_question ("assignmentId", content) values (376, 'New York City');
insert into public.assignment_question ("assignmentId", content) values (538, 'Stebnyk');
insert into public.assignment_question ("assignmentId", content) values (782, 'Nytva');
insert into public.assignment_question ("assignmentId", content) values (83, 'Fenglin');
insert into public.assignment_question ("assignmentId", content) values (422, 'Cholet');
insert into public.assignment_question ("assignmentId", content) values (93, 'Pictou');
insert into public.assignment_question ("assignmentId", content) values (67, 'Tsaritsyno');
insert into public.assignment_question ("assignmentId", content) values (449, 'Lumatil');
insert into public.assignment_question ("assignmentId", content) values (237, 'Senadan');
insert into public.assignment_question ("assignmentId", content) values (708, 'Gushikawa');
insert into public.assignment_question ("assignmentId", content) values (984, 'Jeberos');
insert into public.assignment_question ("assignmentId", content) values (776, 'Qionghai');
insert into public.assignment_question ("assignmentId", content) values (98, 'Ar Rābiyah');
insert into public.assignment_question ("assignmentId", content) values (810, 'Bedalewun');
insert into public.assignment_question ("assignmentId", content) values (419, 'Kolodeznyy');
insert into public.assignment_question ("assignmentId", content) values (621, 'Jaqué');
insert into public.assignment_question ("assignmentId", content) values (35, 'Mala Danylivka');
insert into public.assignment_question ("assignmentId", content) values (713, 'Sulūq');
insert into public.assignment_question ("assignmentId", content) values (3, 'Lisakovsk');
insert into public.assignment_question ("assignmentId", content) values (926, 'Trondheim');
insert into public.assignment_question ("assignmentId", content) values (328, 'Cartagena');
insert into public.assignment_question ("assignmentId", content) values (33, 'Lubowidz');
insert into public.assignment_question ("assignmentId", content) values (278, 'Corail');
insert into public.assignment_question ("assignmentId", content) values (962, 'Taman');
insert into public.assignment_question ("assignmentId", content) values (16, 'Klana');
insert into public.assignment_question ("assignmentId", content) values (635, 'Carvalheira');
insert into public.assignment_question ("assignmentId", content) values (449, 'Aleg');
insert into public.assignment_question ("assignmentId", content) values (620, 'Orange');
insert into public.assignment_question ("assignmentId", content) values (624, 'Ginowan');
insert into public.assignment_question ("assignmentId", content) values (147, 'Minante Segundo');
insert into public.assignment_question ("assignmentId", content) values (538, 'Jieguanting');
insert into public.assignment_question ("assignmentId", content) values (128, 'Hanfeng');
insert into public.assignment_question ("assignmentId", content) values (32, 'Ridder');
insert into public.assignment_question ("assignmentId", content) values (237, 'Caazapá');
insert into public.assignment_question ("assignmentId", content) values (541, 'Soi Dao');
insert into public.assignment_question ("assignmentId", content) values (30, 'Akbarābād');
insert into public.assignment_question ("assignmentId", content) values (207, 'Kilju');
insert into public.assignment_question ("assignmentId", content) values (17, 'Fais');
insert into public.assignment_question ("assignmentId", content) values (338, 'Yantian');
insert into public.assignment_question ("assignmentId", content) values (153, 'Xincheng');
insert into public.assignment_question ("assignmentId", content) values (368, 'Onguday');
insert into public.assignment_question ("assignmentId", content) values (896, 'Matanzas');
insert into public.assignment_question ("assignmentId", content) values (997, 'Lamawan');
insert into public.assignment_question ("assignmentId", content) values (465, 'Shuitou');
insert into public.assignment_question ("assignmentId", content) values (58, 'Santo António');
insert into public.assignment_question ("assignmentId", content) values (739, 'Caqu');
insert into public.assignment_question ("assignmentId", content) values (668, 'San Antonio');
insert into public.assignment_question ("assignmentId", content) values (896, 'Spiczyn');
insert into public.assignment_question ("assignmentId", content) values (202, 'Al Qamşīyah');
insert into public.assignment_question ("assignmentId", content) values (527, 'Alderetes');
insert into public.assignment_question ("assignmentId", content) values (64, 'Jianguo');
insert into public.assignment_question ("assignmentId", content) values (592, 'Alagoinhas');
insert into public.assignment_question ("assignmentId", content) values (178, 'Waekolong');
insert into public.assignment_question ("assignmentId", content) values (692, 'Chợ Mới');
insert into public.assignment_question ("assignmentId", content) values (305, 'Bailu');
insert into public.assignment_question ("assignmentId", content) values (302, 'Adar');
insert into public.assignment_question ("assignmentId", content) values (277, 'Évry');
insert into public.assignment_question ("assignmentId", content) values (121, 'Fontenay-sous-Bois');
insert into public.assignment_question ("assignmentId", content) values (113, 'Vasylkiv');
insert into public.assignment_question ("assignmentId", content) values (573, 'Xujiaqiao');
insert into public.assignment_question ("assignmentId", content) values (246, 'Alingsås');
insert into public.assignment_question ("assignmentId", content) values (642, 'Banjar Asahduren');
insert into public.assignment_question ("assignmentId", content) values (437, 'Venda do Alcaide');
insert into public.assignment_question ("assignmentId", content) values (623, 'Araguaína');
insert into public.assignment_question ("assignmentId", content) values (432, 'Stockholm');
insert into public.assignment_question ("assignmentId", content) values (257, 'Chaka');
insert into public.assignment_question ("assignmentId", content) values (259, 'Janowice');
insert into public.assignment_question ("assignmentId", content) values (666, 'Sémbé');
insert into public.assignment_question ("assignmentId", content) values (847, 'Kruševac');
insert into public.assignment_question ("assignmentId", content) values (885, 'Tinta');
insert into public.assignment_question ("assignmentId", content) values (506, 'Sonsón');
insert into public.assignment_question ("assignmentId", content) values (927, 'Shangganshan');
insert into public.assignment_question ("assignmentId", content) values (677, 'Arroyo Seco');
insert into public.assignment_question ("assignmentId", content) values (556, 'Umeå');
insert into public.assignment_question ("assignmentId", content) values (954, 'San Antonio');
insert into public.assignment_question ("assignmentId", content) values (720, 'Yulao');
insert into public.assignment_question ("assignmentId", content) values (833, 'La Ravoire');
insert into public.assignment_question ("assignmentId", content) values (59, 'Enyerhyetykaw');
insert into public.assignment_question ("assignmentId", content) values (844, 'Algoz');
insert into public.assignment_question ("assignmentId", content) values (825, 'Sukomulyo');
insert into public.assignment_question ("assignmentId", content) values (226, 'Şirrīn ash Shamālīyah');
insert into public.assignment_question ("assignmentId", content) values (1, 'Agrela');
insert into public.assignment_question ("assignmentId", content) values (920, 'Wulan');
insert into public.assignment_question ("assignmentId", content) values (640, 'Ambat');
insert into public.assignment_question ("assignmentId", content) values (101, 'Sar Chakān');
insert into public.assignment_question ("assignmentId", content) values (266, 'Lengkeng');
insert into public.assignment_question ("assignmentId", content) values (194, 'Tolitoli');
insert into public.assignment_question ("assignmentId", content) values (926, 'Bria');
insert into public.assignment_question ("assignmentId", content) values (397, 'Lais');
insert into public.assignment_question ("assignmentId", content) values (308, 'Francisco Beltrão');
insert into public.assignment_question ("assignmentId", content) values (924, 'Campo Formoso');
insert into public.assignment_question ("assignmentId", content) values (763, 'Tanahwulan');
insert into public.assignment_question ("assignmentId", content) values (603, 'Santa Cruz');
insert into public.assignment_question ("assignmentId", content) values (400, 'San Francisco');
insert into public.assignment_question ("assignmentId", content) values (958, 'Kthella e Epërme');
insert into public.assignment_question ("assignmentId", content) values (358, 'Seleuš');
insert into public.assignment_question ("assignmentId", content) values (323, 'Leipsoí');
insert into public.assignment_question ("assignmentId", content) values (885, 'Bailingnao');
insert into public.assignment_question ("assignmentId", content) values (620, 'Jiangluo');
insert into public.assignment_question ("assignmentId", content) values (866, 'Araulí');
insert into public.assignment_question ("assignmentId", content) values (949, 'Huangmei');
insert into public.assignment_question ("assignmentId", content) values (39, 'Shuangcheng');
insert into public.assignment_question ("assignmentId", content) values (581, 'Avignon');
insert into public.assignment_question ("assignmentId", content) values (113, 'Bethel Town');
insert into public.assignment_question ("assignmentId", content) values (277, 'Chumphon');
insert into public.assignment_question ("assignmentId", content) values (7, 'Norberg');
insert into public.assignment_question ("assignmentId", content) values (597, 'Horní Jelení');
insert into public.assignment_question ("assignmentId", content) values (299, 'Kilifi');
insert into public.assignment_question ("assignmentId", content) values (487, 'Miaoqian');
insert into public.assignment_question ("assignmentId", content) values (246, 'Al Matūn');
insert into public.assignment_question ("assignmentId", content) values (193, 'Novoaltaysk');
insert into public.assignment_question ("assignmentId", content) values (479, 'Martapura');
insert into public.assignment_question ("assignmentId", content) values (925, 'Open Stage');
insert into public.assignment_question ("assignmentId", content) values (87, 'Cruzeiro');
insert into public.assignment_question ("assignmentId", content) values (462, 'Návsí u Jablunkova');
insert into public.assignment_question ("assignmentId", content) values (126, 'San Enrique');
insert into public.assignment_question ("assignmentId", content) values (27, 'Bila Krynytsya');
insert into public.assignment_question ("assignmentId", content) values (192, 'Washington');
insert into public.assignment_question ("assignmentId", content) values (932, 'Dishnā');
insert into public.assignment_question ("assignmentId", content) values (248, 'Entre Rios');
insert into public.assignment_question ("assignmentId", content) values (744, 'Santa Marcela');
insert into public.assignment_question ("assignmentId", content) values (677, 'Vsetín');
insert into public.assignment_question ("assignmentId", content) values (465, 'Tayzhina');
insert into public.assignment_question ("assignmentId", content) values (663, 'Oslo');
insert into public.assignment_question ("assignmentId", content) values (557, 'Pico da Pedra');
insert into public.assignment_question ("assignmentId", content) values (904, 'Thị Trấn Mường Khến');
insert into public.assignment_question ("assignmentId", content) values (521, 'Nigel');
insert into public.assignment_question ("assignmentId", content) values (668, 'Risālpur');
insert into public.assignment_question ("assignmentId", content) values (452, 'Tigarunggu');
insert into public.assignment_question ("assignmentId", content) values (852, 'Nkove');
insert into public.assignment_question ("assignmentId", content) values (252, 'Limbi');
insert into public.assignment_question ("assignmentId", content) values (551, 'Halinów');
insert into public.assignment_question ("assignmentId", content) values (247, 'Nogent-le-Rotrou');
insert into public.assignment_question ("assignmentId", content) values (639, 'Stryków');
insert into public.assignment_question ("assignmentId", content) values (975, 'Mayumba');
insert into public.assignment_question ("assignmentId", content) values (449, 'Sa Pá');
insert into public.assignment_question ("assignmentId", content) values (762, 'Tomilino');
insert into public.assignment_question ("assignmentId", content) values (428, 'Banjarsari');
insert into public.assignment_question ("assignmentId", content) values (311, 'Pom Prap Sattru Phai');
insert into public.assignment_question ("assignmentId", content) values (814, 'Casal Velho');
insert into public.assignment_question ("assignmentId", content) values (797, 'Alfeizerão');
insert into public.assignment_question ("assignmentId", content) values (376, 'Sędziejowice');
insert into public.assignment_question ("assignmentId", content) values (167, 'Nepomuceno');
insert into public.assignment_question ("assignmentId", content) values (315, 'Isiro');
insert into public.assignment_question ("assignmentId", content) values (871, 'Mahdia');
insert into public.assignment_question ("assignmentId", content) values (638, 'San Antonio de los Baños');
insert into public.assignment_question ("assignmentId", content) values (581, 'Dandai');
insert into public.assignment_question ("assignmentId", content) values (870, 'El Tejocote');
insert into public.assignment_question ("assignmentId", content) values (803, 'Hukeng');
insert into public.assignment_question ("assignmentId", content) values (377, 'Qal‘ah-ye Fārsī');
insert into public.assignment_question ("assignmentId", content) values (339, 'Kagoro');
insert into public.assignment_question ("assignmentId", content) values (390, 'Velké Svatoňovice');
insert into public.assignment_question ("assignmentId", content) values (191, 'Zhangcunping');
insert into public.assignment_question ("assignmentId", content) values (969, 'Vel’sk');
insert into public.assignment_question ("assignmentId", content) values (239, 'Wudan');
insert into public.assignment_question ("assignmentId", content) values (632, 'Borino');
insert into public.assignment_question ("assignmentId", content) values (300, 'Erie');
insert into public.assignment_question ("assignmentId", content) values (577, 'Philadelphia');
insert into public.assignment_question ("assignmentId", content) values (190, 'Cabaiguán');
insert into public.assignment_question ("assignmentId", content) values (402, 'Żebbuġ');
insert into public.assignment_question ("assignmentId", content) values (633, 'Kashiwa');
insert into public.assignment_question ("assignmentId", content) values (420, 'Khanāşir');
insert into public.assignment_question ("assignmentId", content) values (473, 'Bairro');
insert into public.assignment_question ("assignmentId", content) values (147, 'Bayt Ūlā');
insert into public.assignment_question ("assignmentId", content) values (487, 'Santo Anastácio');
insert into public.assignment_question ("assignmentId", content) values (660, 'Doro Oo');
insert into public.assignment_question ("assignmentId", content) values (803, 'Villaba');
insert into public.assignment_question ("assignmentId", content) values (255, 'Tailing');
insert into public.assignment_question ("assignmentId", content) values (514, 'Veracruz');
insert into public.assignment_question ("assignmentId", content) values (679, 'Bergvliet');
insert into public.assignment_question ("assignmentId", content) values (555, 'Kamina');
insert into public.assignment_question ("assignmentId", content) values (625, 'Moutnice');
insert into public.assignment_question ("assignmentId", content) values (963, 'Malhão');
insert into public.assignment_question ("assignmentId", content) values (92, 'Mrkonjić Grad');
insert into public.assignment_question ("assignmentId", content) values (743, 'Chedao');
insert into public.assignment_question ("assignmentId", content) values (880, 'Shagedu');
insert into public.assignment_question ("assignmentId", content) values (113, 'Solânea');
insert into public.assignment_question ("assignmentId", content) values (221, 'Corredoura');
insert into public.assignment_question ("assignmentId", content) values (44, 'Shanghu');
insert into public.assignment_question ("assignmentId", content) values (454, 'Zhonghualu');
insert into public.assignment_question ("assignmentId", content) values (267, 'Borisovka');
insert into public.assignment_question ("assignmentId", content) values (385, 'Paris 05');
insert into public.assignment_question ("assignmentId", content) values (104, 'Grabów nad Prosną');
insert into public.assignment_question ("assignmentId", content) values (362, 'Az̧ Z̧alī‘ah');
insert into public.assignment_question ("assignmentId", content) values (842, 'Nyköping');
insert into public.assignment_question ("assignmentId", content) values (459, 'Saba Yoi');
insert into public.assignment_question ("assignmentId", content) values (560, 'Guling');
insert into public.assignment_question ("assignmentId", content) values (621, 'São Paio de Gramaços');
insert into public.assignment_question ("assignmentId", content) values (675, 'Sukowidodo Barat');
insert into public.assignment_question ("assignmentId", content) values (795, 'Stockholm');
insert into public.assignment_question ("assignmentId", content) values (390, 'Abadou');
insert into public.assignment_question ("assignmentId", content) values (575, 'Huangtugang');
insert into public.assignment_question ("assignmentId", content) values (347, 'Port Saint Lucie');
insert into public.assignment_question ("assignmentId", content) values (129, 'Pryvol’ny');
insert into public.assignment_question ("assignmentId", content) values (830, 'Gusong');
insert into public.assignment_question ("assignmentId", content) values (7, 'Karangbayat');
insert into public.assignment_question ("assignmentId", content) values (785, 'Divača');
insert into public.assignment_question ("assignmentId", content) values (767, 'Yishui');
insert into public.assignment_question ("assignmentId", content) values (763, 'Trâu Quỳ');
insert into public.assignment_question ("assignmentId", content) values (584, 'Santa Elena');
insert into public.assignment_question ("assignmentId", content) values (96, 'Washington');
insert into public.assignment_question ("assignmentId", content) values (265, 'Aeka');
        `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
